### ISSUE TITLE
Accordion with comparison cards on reveal

### ISSUE THREAD

**Issue by marshjr** [telus/tds-community#110]
## Problem Statement

- As a customer, I would like to have the ability to expand on further information to compare without having to scroll forever
- As a designer, I would like the ability to drop this entire component into my page design and ensure that it will remain consistent, and allow for less scrolling

## Recommendation

<img width="1192" alt="screen shot 2018-09-19 at 11 36 51 am" src="https://user-images.githubusercontent.com/42357996/45765076-22868d80-bc02-11e8-80e5-36075649932c.png">

## Designs

Currently exists in DSM under: Components (not coded) > Feature Content Expand/Collapse
<img width="1099" alt="screen shot 2018-09-19 at 11 54 32 am" src="https://user-images.githubusercontent.com/42357996/45765350-dbe56300-bc02-11e8-8640-bccc74d7f0bc.png">

## Meta

- Willing to design solution: No
- Willing to develop solution: No
- Has workaround: No
- Do any similar components already exist in TDS (core or community): Accordions do exist, however not with comparison cards as the reveal
- Which teams/applications do you think would use this improvement?: HS, MOB, b2b
- High impact: Yes

**Comment by theetrain** [comment]
This is related to https://github.com/telus/tds-core/issues/440

This will be taken up during design review, and potentially added to core or community.

**Comment by theetrain** [comment]
Follow up from DPA design review:

This pattern is no longer acceptable when representing expandable content. We prefer to use Chevrons to denote expandable or collapsed content. Please use the core-expand-collapse component instead.
