### ISSUE TITLE
Skeleton: DSM component

### ISSUE THREAD

**Issue by Christina-Lo** [telus/tds-community#127]
## Description

The Skeleton components need to be built to be responsive in Sketch and usage guidance needs to be added into DSM. 

See #18 
## Reproduction Steps

When I open DSM and pull in the skeleton component, I can not stretch or resize the component without skewing corner radius and changing the height of the object (which should not happen). 

## Reproduction Percentage (if applicable)

10/10 times

## Meta

* TDS version (npm or DSM): v1.0.15
* Willing to develop solution: Yes
* Has workaround: No
* High impact: Yes

## Screenshots

* Include any relevant screenshots

**Comment by varunj90** [comment]
As discussed during DPA meeting Nov 5, @Berjesty will be looking into this one

**Comment by Berjesty** [comment]
This component is added to DSM library with definition, usage criteria and style examples.
![skeleton](https://user-images.githubusercontent.com/25160096/48732813-af53c480-ec0e-11e8-9736-49af73d17d78.png)
