### ISSUE TITLE
Refactor componentWithName utility to use @tds/util-prop-types

### ISSUE THREAD

**Issue by theetrain** [telus/tds-community#129]
## Problem statement

Components such as `community-testimonial` use a local propType `componentWithName` stored in `/shared/utils/propTypes`. This package does not have unit tests, and there is duplicate code in tds-core.

## Recommendation

Let's refactor our community components currently using `componentWithName` to use the newly-released [@tds/util-prop-types](https://github.com/telus/tds-core/releases/tag/%40tds%2Futil-prop-types%401.0.0) package. 

## Designs

N/A

## Meta

- Include component name and version: vX.Y.Z
- Willing to design solution: N/A
- Willing to develop solution: Yes
- Has workaround: Yes
- Do any similar components already exist in TDS (core or community): Yes (see above)
- Which teams/applications do you think would use this improvement? Unsure
- High impact: No

**Comment by theetrain** [comment]
@nicmak has volunteered to patch the testimonial component

**Comment by theetrain** [comment]
Released in [@tds/community-testimonial@1.0.2](https://github.com/telus/tds-community/releases/tag/%40tds%2Fcommunity-testimonial%401.0.2)

**Comment by varunj90** [comment]
assignees have been added on closed issue to reflect power level (points) on community heroes board (coming soon!)
