### ISSUE TITLE
Best practice for Video

### ISSUE THREAD

**Issue by nikaukraine** [telus/tds-community#133]
## Problem statement

Ability to add Video component

## Recommendation

We have 4 existing blocks, we need to define the best practice: 
1. BlockVideo (example: https://www.telus.com/en/about)
2. BlockVideoPicker (example: https://www.telus.com/en/about/company-overview/futurefriendly)
3. BlockHeroWithVideo (example: https://www.telus.com/en/tv/optik/app)
4. BlockVideoBanner (the he which hosts video in Contentful (https://wcpreview.telus.com/en/mobility/videotest)

## Designs
Please see above

## Meta

- Include component name and version: Video
- Willing to design solution: No
- Willing to develop solution: No
- Has workaround: Yes
- Do any similar components already exist in TDS (core or community): No
- Which teams/applications do you think would use this improvement? Site Builder users and anyone else who need it
- High impact: No

**Comment by theetrain** [comment]
It was recommended by @githubjosh to wrap the [PayPal Accessible html5 video](https://github.com/paypal/accessible-html5-video-player) component in order to save us time.

**Comment by nikaukraine** [comment]
Would would be the next step? I it is becoming a high demand at TELUS, will it make sense to make a core video component?

**Comment by simpleimpulse** [comment]
Todo:
- [ ] Find out if isomorphic/starter kit projects have a need for video
- [ ] Developers agree that this is high priority - discuss with designers and assign label
- [ ] Assign a dev to investigate the acceptability of Brian's design, using Paypal's video component.

**Comment by varunj90** [comment]
the core team needs to investigate this

**Comment by agorovyi** [comment]
Closing as Core team is taking care of this.
