### ISSUE TITLE
<SideNavigation /> component that can be used to display multiple links on a page for easier navigation

### ISSUE THREAD

**Issue by Andrew-K-Lam** [telus/tds-community#135]
## Problem Statement

- We need a component that displays all relevant links to other pages or sections within a page, for easier navigation through large amounts of information

## Recommendation

Create a SideNavigation component that takes in Links and Text and displays them as a column, gets hidden on mobile screens, and has an active status if a user is currently on that page or section

## Designs

https://telus.invisionapp.com/share/4BO1W0S6KYT#/329060751_UX_Reference_Architecture_

Updated Nov 30th: https://telus.invisionapp.com/share/FCP1G7TWPEU#/screens/333324266

## Meta

- Willing to design solution: Yes
- Willing to develop solution: Yes
- Has workaround: No
- Do any similar components already exist in TDS (core or community): No
- Does this pattern exist already but isn’t a community component? No
- Which teams/applications do you think would use this improvement? Any
- High impact: Yes?

**Comment by varunj90** [comment]
hey @Andrew-K-Lam this will be brought to the design leads meeting this friday - we'll reach out to you shortly.

cc: @lucylist

**Comment by Andrew-K-Lam** [comment]
cc: @elenaverling

**Comment by varunj90** [comment]
this is good w.r.t design @Andrew-K-Lam let us know if you're contributing this to community!

**Comment by theetrain** [comment]
The React component has been released: [@tds/community-side-navigation](https://github.com/telus/tds-community/releases/tag/%40tds%2Fcommunity-side-navigation%401.0.0)

**Comment by varunj90** [comment]
assignees have been added on closed issue to reflect power level (points) on community heroes board (coming soon!)

**Comment by varunj90** [comment]
This is now released in code and DSM and available on https://tds.telus.com/community/index.html#side-navigation
