### ISSUE TITLE
Flexibility of padding 

### ISSUE THREAD

**Issue by Mariefhrmnn** [telus/tds-community#157]
## Problem statement

The TSD_core library propose a component named ‘LISTS’. 
There is a padding on the left  (green color) of the bullet points. This padding is not flexible and doesn’t permit to create a more structured layout. 

## Recommendation

Description of the proposed solution
I would like to have more flexibility to use this list without padding in front of the bullet points. In that case, we could align all the texts to have a better visual design.

## Designs

- Screenshots
<img width="882" alt="screen shot 2018-12-18 at 4 04 40 pm" src="https://user-images.githubusercontent.com/44266628/50227510-e33c1a00-0373-11e9-9aa6-6c42186b7443.png">

- Sketch file: 
     > what we have currently: https://telus.invisionapp.com/d/main/#/console/16159628/337702564/preview
     > what we would like: https://telus.invisionapp.com/d/main/#/console/16159628/337702563/preview

- TDS website reference: https://tds.telus.com/#lists

## Meta

- Include component name and version: 2.0.2
- Willing to design solution: No
- Willing to develop solution: No
- Has workaround: Yes
- Do any similar components already exist in TDS (core or community): Yes https://tds.telus.com/components/index.html#lists
- Which teams/applications do you think would use this improvement? Dope Jackalope / @Berjesty / @invalidred / @Jeffrey-Chang 
- High impact: No

**Comment by varunj90** [comment]
Hi @Mariefhrmnn - can you move this issue to tds-core using this link https://github.com/telus/tds-core/issues/new/choose

closing this as it's not tds-community
