### ISSUE TITLE
Universal pattern for close and 'x'

### ISSUE THREAD

**Issue by varunj90** [telus/tds-community#175]
Based on the discussion on February 4, DPA realized that a pattern needs to be defined for close and x icon next to it. Currently, lots of variations exist and we need to work together in defining a standard way.

## Variations
Close x
close x
x Close
x close

## Problem Statement

- As a designer, I would like to see a consistent pattern for 'Close', 'x' so that the customer sees a consistent experience across all TELUS sites

## Recommendation

Universal pattern for "close" will be using the **close icon (x with circle)**.
When the function is a "remove", "clear" etc., a **text link with the word "remove" or "clear"** to perform the action.

## Designs

Attached mock-ups of Terms and Condition footnote and _modal for visual reference

<img width="670" alt="60049196-c45c6e80-969b-11e9-879a-416cd4a8939b" src="https://user-images.githubusercontent.com/32107656/60052511-764b6900-96a3-11e9-850b-f4dc61076a76.png">

<img width="633" alt="60049198-c4f50500-969b-11e9-8a68-54044516501d" src="https://user-images.githubusercontent.com/32107656/60052513-78adc300-96a3-11e9-908b-2aaa252de5e0.png">

### User stories

(This section is intentionally left blank. User stories and acceptance criteria go here.)

**Example:**

Scenario: Displaying the component

Given text is provided
Then the text is displayed as a child
And the text size matches core-text `medium`

### Out of scope

(This section is intentionally left blank. Features or items that were deliberately left out of scope during design intent or may be mistaken as within scope are noted here. Link to related issues if possible.)

## Meta

- Willing to design solution: Yes/No
- Willing to develop solution: Yes/No
- Has workaround: Yes/No
- Do any similar components already exist in TDS (core or community): Yes/No
- Does this pattern exist already but isn’t a community component? (include url)
- Which teams/applications do you think would use this improvement?
- High impact: Yes/No

**Comment by varunj90** [comment]
@DougTelus and @twirlingsky: Please add recommendations or edit this ticket,

cc: @DanGenuardi and @stephlao

**Comment by DougTelus** [comment]
I believe the pattern Laurel described to be the best variation.
Lowercase 'close' styled with TDS href link. DecorativeIcon symbol="times" to the right.
close x

**Comment by varunj90** [comment]
is the short term solution @DougTelus ? Or are we going to elaborate or work on this pattern further?

**Comment by DougTelus** [comment]
@twirlingsky Were there any CX/accessibility considerations or testing scenarios that helped inform the "close x" pattern your HS has been using?

@varunj90 I'd like to avoid exploring this further if HS has already done the work and level set on this pattern.

**Comment by gkychow** [comment]
@DougTelus @twirlingsky - Besides the order of the "x" and "close", can we also align on spacing between elements, spacing around the whole thing, size of the "x", and text size as well?

**Comment by DanGenuardi** [comment]
I found this example within the TDS design guidelines site. 
<img width="1004" alt="screen shot 2019-02-13 at 2 35 03 pm" src="https://user-images.githubusercontent.com/39997967/52796611-29df8500-3042-11e9-8ed5-734081260ac0.png">

We just use the "x" as the dismiss button within this notification box. Is this something we can leverage? This is on TDS core so I would assume that this has been tested for accessibility.

**Comment by varunj90** [comment]
DPA meeting 

1. x and close with alt on desktop; mobile can have x only (due to limited space) with alt
2. do consider when doing in french
3. pass in language instead of word for consistency and provide appropriate options in usage criteria

**Comment by varunj90** [comment]
the visual for this needs to be mocked - @Christina-Lo can add to this

cc: @DougTelus @twirlingsky

**Comment by Christina-Lo** [comment]
Universal pattern for "close" will be using the **close icon (x with circle)**. In conversations with accessibility, using the "X" without the word is a recognizable design pattern and is passable.
When an item needs to be removed, use **text link** with the word "remove" to remove items
Attached mock-ups of _Terms and Condition footnote_ and _modal for visual reference
<img width="670" alt="Screen Shot 2019-06-24 at 4 16 24 PM" src="https://user-images.githubusercontent.com/42220619/60049196-c45c6e80-969b-11e9-879a-416cd4a8939b.png">
<img width="633" alt="Screen Shot 2019-06-24 at 4 18 28 PM" src="https://user-images.githubusercontent.com/42220619/60049198-c4f50500-969b-11e9-8a68-54044516501d.png">

**Comment by DougTelus** [comment]
I updated the story above to reflect the decisions @Christina-Lo, accessibility, contributing and DPA members resolved to. 👍

**Comment by mejsullivan** [comment]
@varunj90 the "X" needs alternative/descriptive text as a standard to be accessible. Is the a part of the component? Is there always alternative/descriptive text on the "X"? 

Is the component keyboard accessible? 
Does "esc" also work with the "X" is available?
I don't see the focus state?

Let me know if all of that passes :).
