### ISSUE TITLE
(core team developing) new: Filters Tags

### ISSUE THREAD

**Issue by nicmak** [telus/tds-community#189]
## Problem Statement

As a customer I would want flexible way to filter through products I am looking for based on the filter tags I have selected (Whether I selected one or more tags).

**DEMO: Component is built already in Community-Site-Builder**
Check in DPA GDrive
**Issue Ticket written in Community-Site-Builder**
[https://github.com/telus/community-site-builder-blocks/issues/292](url)

## Recommendation
 https://telus.invisionapp.com/share/N4TI3OZQK8C#/379472936_XL_-_1200px_--_Filters_-_01

<img width="1096" alt="Screen Shot 2019-11-20 at 3 20 54 PM" src="https://user-images.githubusercontent.com/22402633/69286941-5fa13380-0ba9-11ea-9487-0121077df57e.png">

## Design intent

**Tags** - first element in a larger filter system

**Usage**: Represent information used in catalogue experiences and allows for filtering of that content. The customer will expect the same action in the same general area/catalogue view.
Used in sets that contain at least two options, to represent a single selection. The customer is able to multi-select available tags.

**Principles**: Compact, relevant, focused (makes easy to sort),
An alternative to toggle buttons or checkboxes.

**Placement**: can be shown underneath a search field, can be used inside other components or a sidebar and can wrap.  

**Behaviour**: Click or Tap a tag to select it. Multiple tags can be selected or unselected

## Meta

- Willing to design solution: No
- Willing to develop solution: Yes
- Has workaround: Yes/No
- Do any similar components already exist in TDS (core or community): Yes (Community-Tabs)
- Does this pattern exist already but isn’t a community component? (include url)
- Which teams/applications do you think would use this improvement?
- High impact: Yes/No

## Acceptance Criteria

All ACs and documentation is captured in this GDoc: https://docs.google.com/document/d/1bHc5NNkaMuYK9FOqdSgMyhQhLamal2H2OaPDOXENcBY/edit#

**Comment by varunj90** [comment]
@twirlingsky and @gkychow will be doing a design review to see what pattern works!

**Comment by brianlam1** [comment]
Just as an FYI, Site Search uses Pilters. It is not really "filtering" for all intents and purposes, but rather moving between different site-search engines.

@abansil on my team is looking at something different for us because these don't scale well, and in mobile its horrendous.

[https://www.telus.com/en/on/search](https://www.telus.com/en/on/search)

**Desktop**
![screen shot 2019-03-04 at 1 24 44 pm](https://user-images.githubusercontent.com/31013883/53763996-fcd40480-3e80-11e9-918c-cb7fd5d0ac37.png)

**Mobile**
![screen shot 2019-03-04 at 1 26 54 pm](https://user-images.githubusercontent.com/31013883/53764086-3573de00-3e81-11e9-8a12-f9b865519aff.png)

**Comment by twirlingsky** [comment]
Current designs: https://telus.invisionapp.com/d/#/console/16401801/351196659/preview

XL prototype: https://telus.invisionapp.com/d/#/console/16401801/350989521/preview

Have reviewed these with Gary & Beth. Need to put them through a round of usability testing next.

**Comment by varunj90** [comment]
hey @twirlingsky any updates from usability testing? any next steps?

**Comment by varunj90** [comment]
@twirlingsky to look for the usability testing results for this one.

will also be discussed at design jam

**Comment by varunj90** [comment]
@twirlingsky and Thiveya will jam on this together

**Comment by twirlingsky** [comment]
InVision Project: https://telus.invisionapp.com/d/main#/projects/prototypes/18274872
HS Catalogue Ticket:

**Comment by twirlingsky** [comment]
![screencapture-telus-invisionapp-d-main-2019-11-18-14_56_29](https://user-images.githubusercontent.com/22402633/69101147-b248e700-0a13-11ea-97a3-ad5be2001cb3.png)

**Comment by mike-bunce** [comment]
Added acceptance criteria at the top of this GitHub issue

**Comment by twirlingsky** [comment]
Updated design recommendation and intent at the top of this GitHub issue

**Comment by varunj90** [comment]
hey @alexgunnarhenderson would you like to contribute this component to tds community?

**Comment by varunj90** [comment]
tds core team will be taking on the development for this component

**Comment by theetrain** [comment]
[`@tds/community-tags@1.0.0`](https://github.com/telus/tds-community/releases/tag/%40tds%2Fcommunity-tags%401.0.0) is released!
