### ISSUE TITLE
Preview Card

### ISSUE THREAD

**Issue by elenaverling** [telus/tds-community#199]
## Problem Statement

Due to a security breach, we need to move the TELUS Digital blog onto SiteBuilder from October CMS. Currently, none of the TDS cards would fit the requirements so I'm proposing myself and Hamed/Andrew Lam create a 'preview card' community component.

## Recommendation
Each preview card will display the title, date, author, tag and relevant image. Mandatory fields are body and image. Designs have been approved by DPA. The card will eventually have the ability to be filtered by category and author, so both will be clickable. However, this is out of scope - potential MVP2.

## Design intent

**PreviewCard large (desktop):**
- Title: Truncation will occur after 70 characters (so text spans roughly 2 lines)
- Hover state to include drop shadow and image (zoom) enlargement similar to this: https://www.telusinternational.com/
- Recommended image dimensions 369 x 269px
- Image border radius: 4;4;0;0
- Image border 1px: #F7F7F8
- Vertical padding: 48px 
- Side padding: 32px
- Padding between text 16px

**PreviewCard short (desktop):**
- Title: Truncation will occur after 70 characters (so text spans roughly 2 lines)
- Hover state to include drop shadow and image (zoom) enlargement
- Recommended image dimensions 268 x 200px
- Image border radius: 4;4;0;0
- Image border 1px: #F7F7F8
- Vertical padding: 32px 
- Side padding: 16px
- Padding between cards: 32px

**PreviewCard small (iPhone SE):**
- No hover state
- Pressed state: shadow appears
- Image border radius: 4;4;0;0
- Image border 1px: #F7F7F8
- Vertical padding: 32px 
- Side padding: 24px
- Cards will now appear stacked one on top of each other
- 16px padding around card (top bottom left right)

## Designs

Blog landing desktop: https://telus.invisionapp.com/share/BWR0G24M48A#/354226611_Blog_Landing_UI_

Blog article desktop: https://telus.invisionapp.com/share/BWR0G24M48A#/354403664_Blog_Article_UI_

Blog landing mobile: https://telus.invisionapp.com/share/BWR0G24M48A#/354226610_iPhone_XS

Blog article mobile: https://telus.invisionapp.com/share/BWR0G24M48A#/355033834_Blog_Article_XS_

**Added the Sketch usage notes to TDS Community DSM (Craft)
Added the 4 cards to TDS Community InVision https://telus.invisionapp.com/share/2WFVPUOACPQ
Added WIP Sketch file https://invis.io/a/WN5N0QWQ56KU**

- Willing to design solution: Yes
- Willing to develop a solution: Yes 
- Has workaround: No
- Do any similar components already exist in TDS (core or community): No
- Does this pattern exist already but isn’t a community component? (include url)
- Which teams/applications do you think would use this improvement? Majority of TELUS, Halo, BRC, About team
- High impact: Yes

**Comment by theetrain** [comment]
The Preview Card component is now available!
- DSM: tds_community v1.0.18
- Release notes: [@tds/community-preview-card@1.0.0](https://github.com/telus/tds-community/releases/tag/%40tds%2Fcommunity-preview-card%401.0.0)
- npm: https://www.npmjs.com/package/@tds/community-preview-card
