### ISSUE TITLE
New tab to save multi card 

### ISSUE THREAD

**Issue by Mariefhrmnn** [telus/tds-community#200]
## Problem Statement

- As a customer I would like to add/save multi cards on my profile so that I can to pay different bills that I have.

## Recommendation

The proposed solution is to develop a clean simple tab structure with the purple line highlighting the selected section. And for every selected section, the content will change. 

## Designs

- Screenshots
![Screen Shot 2019-04-01 at 12 32 41 PM](https://user-images.githubusercontent.com/44266628/55344006-4ca2ed00-547a-11e9-8782-fb117d5cc2f2.png)
![Screen Shot 2019-04-01 at 12 32 58 PM](https://user-images.githubusercontent.com/44266628/55344013-4f054700-547a-11e9-80ea-d2248b232a35.png)

- InVision links
> XL: https://telus.invisionapp.com/d/main/#/console/16377283/355503921/preview
> M: https://telus.invisionapp.com/d/main/#/console/16377283/355503918/preview
> XS: https://telus.invisionapp.com/d/main/#/console/16377283/355503915/preview

## Acceptance criteria
  DO NOT REMOVE THIS SECTION

  Things to consider when writing acceptance criteria (ACs):

  Things to think about:

  -> What needs to be done to make this accessible?
  -> Visual properties
  -> Interactions
  -> Documentation
  -> Considerations if changes need to be mirrored to tds-core and tds-community
  -> Are there any responsive behaviours or visual differences?
  -> French considerations, do symbols or text need to be rendered in a certain order or manner?
  -> Text considerations, do we need SVGs, symbols, superscript text, or other special formatting?
  -> Make sure the ACs do not overly specify names of props. Try to stay generic and descriptive. Describe the interactions and behaviours of your component.

  Given...
  When...
  (And...)
  Then...
  (And...)

  Example:

    Given I am displaying the community-testimonial component

      When I supply an image
      And I supply testimonial text
      And I supply info
      Then the testimonial is displayed within a card with testimonial text
      And the testimonial image is displayed to the left of its info

      When I do not supply an image
      And I supply testimonial text
      And I supply info
      Then the testimonial is displayed within a card with testimonial text
-->

This section is intentionally left blank. See [story writing process](https://github.com/telus/tds-community/blob/master/guide/Community_Backlog.md#5-story-writing).

### User stories

(This section is intentionally left blank. User stories and acceptance criteria go here.)

**Example:**

Scenario: Displaying the component

Given text is provided
Then the text is displayed as a child
And the text size matches core-text `medium`

### Out of scope

(This section is intentionally left blank. Features or items that were deliberately left out of scope during design intent or may be mistaken as within scope are noted here. Link to related issues if possible.)

## Meta

- Willing to design solution: Yes
- Willing to develop solution: Yes
- Has workaround: No
- Do any similar components already exist in TDS (core or community): Yes
- Does this pattern exist already but isn’t a community component? (include url) No
- Which teams/applications do you think would use this improvement? Dope Jackalope
- High impact: Yes

**Comment by invalidred** [comment]
@donnavitan  make sure the content in the tabs panel does not affect content in other tabs panel. For example a form in Tab A should not interact with a from in Tab B.
@apurvray visual queue when tabs are overflow.
@owestinTelus https://inclusive-components.design/tabbed-interfaces/

**Comment by owestinTelus** [comment]
Remember to document accessibility considerations should be based on

**Desktop:**
• Keyboard alone
• Text Resize
• Colour Contrast
• Windows High Contrast Mode
• Reduce Motion
• Screen reader

**Mobile Web:**
• Switch access/control
• Pinch ZoomColour Contrast
• Inverse Colour/Grayscale
• Reduce Motion
• Screen reader

**Mobile Native Apps:**
• Switch access/control
• Larger Text
• Colour Contrast
• Inverse Colour/Grayscale
• Reduce Motion
• Screen reader (edited)

**Comment by varunj90** [comment]
my telus is not pursuing this, using select vs tags!
