### ISSUE TITLE
ProgressBar alternate use for Rewards

### ISSUE THREAD

**Issue by meg-bee** [telus/tds-community#206]
## Problem statement

As a user, I would like to see how close I am to affording a reward on TELUS Rewards

In the current launched version of the reward details page, when a customer does not have the required points balance to afford an award, they are presented two CTAs to go back to the catalogue or learn about rewards. They’re missing two crucial bits of information: their current points balance, and a way to set the reward as a goal to redeem in the future.

## Recommendation

Recommended changes: showing the customer’s point balance along with the ‘cost’ of the reward. This information could be supplemented with a visual representation of the points gap by using a version of the progress bar component - https://tds.telus.com/community/index.html#progress-bar
We are also adding the ability for the customer to save the item to their Wishlist, so that they can return later to redeem it once they have enough points.

## Design intent

As a customer, I want to know how close I am to being able to afford a reward item, and I want to be able to save it so that I can redeem for it later.

The information _can_ be shown in an alphanumerical format only, but we felt that showing a visual indication of the points gap would give the customer a more engaging experience, and create more excitement when the progress bar is close to finishing. We’ve also seen a progress indicator used in other common loyalty programs, like Scene and Starbucks, so this is a mental model a lot of customers will be familiar with. Examples attached here
<img src="https://user-images.githubusercontent.com/49487743/56293604-5d4c9780-60f7-11e9-9cea-1daa4f6b1ff0.PNG" width="250" />
<img src="https://user-images.githubusercontent.com/49487743/56293605-5d4c9780-60f7-11e9-8a84-960619525761.PNG" width="250" />

Updated design showing the thinner progress bar option can be found here: https://architech.invisionapp.com/share/PYRLF787BTQ
The user's points balance is shown as a fraction of the points needed to redeem for the item. The progress bar augments this information with a visual representation of the percentage-complete progress.

## Acceptance criteria, documentation, designs

See the [TDS Community Progress Bar Google Doc](https://docs.google.com/document/d/1EanHpck6xfrmphktlnElmkEfbwVSDABmpMIT3YNA124/edit#) for full details related to acceptance criteria, motivation, designs, accessibility, and documentation.

InVision link: https://telus.invisionapp.com/share/DNV56L0AQS6

## Out of scope
* Further user research on customer understanding of presentation of current progress bar
* Further audit and design for complex progress bar (stacked bars, single/multiple limits, parent and child progress bar relationships, sibling progress bar relationships)
* Animation of progress bar

## Meta
- Include component name and version: vX.Y.Z
- Willing to design solution: Yes
- Willing to develop solution: Yes
- Has workaround: Yes
- Do any similar components already exist in TDS (core or community): Yes, usage of progress bar component https://tds.telus.com/community/index.html#progress-bar
- Which teams/applications do you think would use this improvement? TELUS Rewards
- High impact: No

**Comment by varunj90** [comment]
DPA meeting notes
- showcased the progress bar on the overview page, thinner progress bar
- opportunity to squish the content

Next steps:
- Have a proposal from TELUS Rewards

**Comment by meg-bee** [comment]
I've updated the Invision link above with the updated version of the progress bar (thinner, less surrounding text). I've also attached some examples from other loyalty programs that informed our design intent. @varunj90 if I move this ticket to design review, will one of the DPA designers have a look and let me know if the usage of the progress bar requires the full DPA process, or if it is a use case of the component? Thank you for your help on my first go-around with the DPA process!

**Comment by varunj90** [comment]
hey @meg-bee added you to the agenda today to go over the updates to this ticket!

**Comment by varunj90** [comment]
April 22 DPA Discussion

- Opportunity to update code and DSM of progress bar component to have thick/thin
- Differentiate via colors? Use the TDS green and progress bar colors
- Usage criteria can indicate what should be used for points / or x amount of data

Next steps

- Enhance code and design for progress bar component, along with usage criteria in docs
- Look into existing TDS box spacing [Donna]

This is going in the story writing phase: https://github.com/telus/tds-community/blob/master/guide/CommunityBacklog.md#5-story-writing

cc: @theetrain

**Comment by nathanmarshall** [comment]
@meg-bee Do you have a developer/designer pair lined up for this ticket?

**Comment by nathanmarshall** [comment]
@meg-bee  User stories have been updated for this ticket. Please review when possible.

**Comment by meg-bee** [comment]
@nathanmarshall I don't have a DPA designer lined up, no. Does this ticket require further design than what's been captured already? I believe we have development covered, our team spoke with Ally Hui on the MyTELUS team about using the thin progress bar component, and she'd provided them with what they need. 
Thank you for updating the user stories! They look good to me.

**Comment by varunj90** [comment]
hey @meg-bee the progress bar component needs to be enhanced both in design and code.

in addition, we recommend you to enhance the component so we're not just keeping the code private and is shareable.

cc: @ah-arch and @apurvray can you assist please

**Comment by ah-arch** [comment]
I referred them to the [usage bar](https://github.com/telus/my-account-overview/tree/master/app/src/ui/components/ServiceCards/ComponentUsage/UsageBar) for the overview project ([invision](https://telus.invisionapp.com/d/main#/console/16275051/337880622/preview)). However, that was set to a height of **10px** and launched before the TDS community version was available.

I am not aware of the requirements for this project.

**Comment by varunj90** [comment]
DPA 29 April

Based on our discussion, @apurvray (with support from @Christina-Lo ) will add update progress bar community component in DSM to enable the feature required in this ticket.

on completion, either a developer from your team @meg-bee or @ah-arch, if you can update code to the component that would be great. this way both of you will be able to consume tds community component in your application

**Comment by varunj90** [comment]
- naming components (small, large, adding a thin version)
- Apurv to ask Ally if she can contribute to the community component
- Please consider usage guidelines

**Comment by ah-arch** [comment]
The [community component](https://tds.telus.digital/community/index.html#progress) currently has 4 variants:
![Community Variants](https://user-images.githubusercontent.com/4450690/57255060-de28f000-7020-11e9-9492-229ddfef6ea1.png)

However, the [overview app](https://telus.invisionapp.com/d/main#/console/16275051/337880622/preview) currently uses 2 different variants:
![Project Variants](https://user-images.githubusercontent.com/4450690/57255078-e6812b00-7020-11e9-98c9-c55cbd87d9e8.png)
(red with stripes, lighter green, 10px heights)

**Comment by theetrain** [comment]
@apurvray to take back the following:

- [ ] Align on variants for community-progress vs the ones used by My TELUS (hashed red vs red, green vs accessible green, disabled vs Athens Grey, etc)
- [ ] Assure symbols available in DSM get aligned with code

**Comment by Christina-Lo** [comment]
@apurvray had a chat with @DanGenuardi, here are some notes:

- Colour: red, accessible green, athens grey
- patterned bars are for shared data usage and solids are for individuals
- changes will need to be made to current progress bar to align with design, colour, sizing, and naming(DSM)

@apurvray will attach designs once those are finalized

**Comment by varunj90** [comment]
@apurvray can you share the designs here, thanks!

**Comment by DougTelus** [comment]
If this design hasn't been tested, they are good candidates for Validately unmoderated testing to see if users understand the context of red, green, grey colours/patterns with regards to the status of their various data usages.

> * Colour: red, accessible green, athens grey
> * patterned bars are for shared data usage and solids are for individuals
> * changes will need to be made to current progress bar to align with design, colour, sizing, and naming(DSM)

**Comment by apurvray** [comment]
Designs uploaded here :
https://telus.invisionapp.com/project/17860368 

Also added them to the DSM under - Progress (Updated)

**Comment by apurvray** [comment]
![Screenshot 2019-06-24 14 02 09](https://user-images.githubusercontent.com/32710185/60041166-acc7ba80-9688-11e9-8c6d-8a263c66c63e.png)
![Uploading Screenshot 2019-06-24 14.02.02.png…]()
![Uploading Screenshot 2019-06-24 14.01.53.png…]()

**Comment by apurvray** [comment]
@DougTelus Lets test this out before we go into dev 
I will also create some recipes (a combination of some of these) that we might to test. Also, the usage page needs a reset with unlimited plans/ FastPass. So we might want to include that in it as well.

**Comment by varunj90** [comment]
based on DPA discussion
1. we will go ahead with existing designs
2. apurv to added usage criteria
3. apurv to connect with berjesty and dan - usage team

**Comment by varunj90** [comment]
@apurvray the story is ready to be reviewed for the ACs

**Comment by agorovyi** [comment]
While refactoring this component please make sure to use `styled-components`. I've added an additional AC to cover that.

**Comment by varunj90** [comment]
@jraff is converting this component to styled-components and adding the new feature requested

**Comment by mike-bunce** [comment]
Usability testing is currently taking place.

**Comment by varunj90** [comment]
one round of testing is completed

@donnavitan will consolidate notes, and provide direction forward.

**Comment by varunj90** [comment]
@donnavitan to provide an update this week.

**Comment by donnavitan** [comment]
* Updated main description with the latest design specs and documentation
* Must create a new community ticket to address outstanding considerations
   * Further user research on customer understanding of presentation of current progress bar
   * Further audit and design for complex progress bar (stacked bars, single/multiple limits, parent and child progress bar relationships, sibling progress bar relationships)
   * Animation of progress bar

Next steps:
* Review with developers to edit/update code acceptance criteria

**Comment by theetrain** [comment]
This is now ready for development. The original post was updated:

* ACs, docs, intent, accessibility: https://docs.google.com/document/d/1EanHpck6xfrmphktlnElmkEfbwVSDABmpMIT3YNA124/edit#
* Designs: https://telus.invisionapp.com/share/DNV56L0AQS6

**Comment by theetrain** [comment]
This update has been released!

* _tds_community DSM Library v1.0.10
* [`@tds/community-progress@2.0.0`](https://github.com/telus/tds-community/releases/tag/%40tds%2Fcommunity-progress%402.0.0)
* [Documentation for Progress on tds.telus.com](https://tds.telus.com/community/index.html#progress-bar)
