### ISSUE TITLE
Component level loading spinner

### ISSUE THREAD

**Issue by apurvray** [telus/tds-community#216]
## Problem statement

- As a user , I would like to see if the action I performed on a component that sends a server side request was successful or failed  , so that I can take an informed next step_

## Recommendation

- Adding a smaller version of the spinner with 'white-out' on smaller components like links or checkboxes or toggle buttons with a size of 24x24 (thats the line height of our medium type used with these elements usually). 

## Design intent

- As a user , I would like to see if the action I performed on a component that sends a server side request was successful or failed  , so that I can take an informed next step_

Narrative

Whenever the users use a component where it needs to make a server call we currently have no established pattern to indicate progress or success or failure to complete that task. e.g. Someone enables or disables internet using a check box or a toggle. We don't show any indicators if its taking a while or fails. 

## Designs

![download-current-bill-spinner](https://user-images.githubusercontent.com/32710185/57387605-a5a22700-7184-11e9-9270-5e4ee530909c.gif)

Just reduce size of the spinner to 24px and scale the white background to the size of teh parent element. 

## Acceptance criteria

This section is intentionally left blank. See [story writing process](https://github.com/telus/tds-community/blob/master/guide/Community_Backlog.md#5-story-writing).

### User stories

(This section is intentionally left blank. User stories and acceptance criteria go here.)

**Example:**

Scenario: Displaying the component

Given text is provided
Then the text is displayed as a child
And the text size matches core-text `medium`

### Out of scope

(This section is intentionally left blank. Features or items that were deliberately left out of scope during design intent or may be mistaken as within scope are noted here. Link to related issues if possible.)

## Meta

- Include component name and version: vX.Y.Z
- Willing to design solution: Yes
- Willing to develop solution: Yes
- Has workaround: Dont know
- Do any similar components already exist in TDS (core or community): Yes 
- Which teams/applications do you think would use this improvement? Overview
- High impact: No

**Comment by varunj90** [comment]
Hi @apurvray given spinner is a core component - please reopen this issue in tds-core https://github.com/telus/tds-core/issues/new/choose

thank you!
