### ISSUE TITLE
new: Terms & conditions component

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#23]
## Problem Statement

As a customer I need the ability to read the terms and conditions of products, services and pricing so that I may understand with clarity what is included/excluded and my legal obligations.

As a marketer I need the ability to provide specific details for products, services and pricing messages when it cannot be reasonably explained within the marketing copy.

**Requirements**
- legal key _${LEGAL.description-of-legal-item}_ reference in sitebuilder that embeds a consistently styled asterisk or numerical annotation as a hypertext link (or button _tbd_) within pricing lockups or body copy. _(see pg.55 [TELUS Content Standards](https://docs.google.com/document/d/1hEAbRxEeKDwruhYKsNnF-788rZ_W10gyAO2-0IPM5uo/edit?usp=sharing))_
- legal key link displays the specific legal copy in a disclosure notifier on-screen with a close button.
- accessibility enablement - read-by text that describes the label first _'Terms & Conditions'_ followed by _'annotation [1]. [legal copy]'_. The next tab to page element should be a [X] close button to dismiss the disclosure notifier.
- markdown support (bold, etc.) to the content of legal notes inside of [G] Legal in Contentful

**Considerations**
- do not use small type or any distracting elements that could undercut/hide the disclosure
- If only one annotation is required, use superscript asterisk. For example, “Get a free gift when you bundle TELUS services*, and in legal copy, it would be “*Conditions apply.”
- If only one annotation is required, when possible place elaborative copy in-page with the language or element in question.
- A clickable area of 16x16 pixels would be ideal. _(may require text link to be styled as a button)_

**Usage**
[v1 - InVision Prototype - XL](https://telus.invisionapp.com/share/3JPNP5XNFKD#/337359350_WHP_XL_-_Legal_Copy_Placement_-_A1)
[v2 - InVision Prototype - XL](https://telus.invisionapp.com/share/8UPTZOT2QNB#/339313798_WHP_XL_-_Legal_Copy_Placement_-_C)

[v1 - InVision Prototype - XS](http://telus.invisionapp.com/share/EHPTJ8FWNX5#/339024731_WHP_-_XS)
[v2 - InVision Prototype - XS](https://telus.invisionapp.com/share/TMPTEYF46GU#/339146574_WHP_-_XS)

[v1 - InVision Prototype - XL - Pricing with legal](https://telus.invisionapp.com/share/SWQHTM0XE54#/346608601_XL)

## Research
[Research deck](https://docs.google.com/presentation/d/14_bpgQZhaBboRyTVkYlEgWFyUJZw3fRifkABlrRfJ7k/edit?usp=sharing)
[Existing SiteBuilder Component](https://github.com/telus/redux-contentful/blob/master/src/components/Legal/WithLegal.jsx)
_TELUS Production examples (as seen in research deck)_
**Pattern A, B** - numbered superscript that links to a slide out panel and highlighted the right numbered item.
**Issues** - click area is too small, annotation link and drawer both present accessibility issues with browser screen readers, feature is not consistent on mobile devices (implementation and functionality), 

**Pattern C** - terms and conditions are in an accordion and the user must navigate up and down the page to find the relevant numbered annotation.
**Issues** - the correlation of annotation to legal line item is not clear, the accordion is accessible and the legal text inside can be read by screen reader however, the accessible text to open the accordion is not very good.

**Pattern D** - example page has been updated with in-page ToC copy and generic ToC language in an accordion.

**Pattern E** - example page has been updated with unlinked numbered annotations and a ToC accordion with numbered legal descriptions

**Pattern F** - nutcracker flow, [Terms and conditions for Internet and TV deals and bundles] new page load under [service terms]

https://www.telus.com/en/bc/tv/new/plans#/landing (slide in)
https://www.telus.com/en/bc/mobility/plans?linktype=nav (accordion)

* Teams/applications that could use this improvement: All teams, All applications
* High impact: Yes

**Comment by DougTelus** [comment]
I captured some extra complexity of the Terms & Conditions as it exists today. Some accessibility concerns as well as what other companies are doing.

https://docs.google.com/presentation/d/14_bpgQZhaBboRyTVkYlEgWFyUJZw3fRifkABlrRfJ7k/edit?usp=sharing

**Comment by simpleimpulse** [comment]
@DougTelus to present findings on Dec 17 2018 to DPA.

**Comment by DougTelus** [comment]
I will send out emails to different experts within TELUS with specific areas of the solution to provide feedback on.

**Comment by twirlingsky** [comment]
In Home Solutions, we have a collapsed configurator panel that is sticky to the bottom of the page. Would this solution overtake that sticky or cause issue (competing sticky footer elements)?

**Comment by Berjesty** [comment]
@DougTelus Reviewed designs, great work! I like how there are multiple view points to terms and conditions where they can be accessed via the bottom part of the page even if customer doesn't click on each respective term within context. 

I prefer version 1 where the terms description covers half the page. Looks visually less disrupting and easier to get back to the previous screen.

**Comment by DougTelus** [comment]
> I prefer version 1 where the terms description covers half the page. Looks visually less disrupting and easier to get back to the previous screen.

This is in regards to the mobile v1 design?

**Comment by Berjesty** [comment]
Yes that’s correct.

**Comment by DougTelus** [comment]
B2B user testing has started to reveal users find it off-putting when there is a large number of legal annotations per page as well as seeing numbered legal annotations beside numbered prices.

**Comment by invalidred** [comment]
There is a misalignment between what is needed and what was designed. Lets have a discussion with @sketchidea  around this. @sketchidea to provide more info.

**Comment by sketchidea** [comment]
There are a few concerns around this component, after discussing with the DPA dev leads - it looks like this is owned by Global Elements - so we should reach out to Brian Lam's team.

**Comment by DougTelus** [comment]
I sent a review email out with the github link and invision designs. @brianlam1 was copied on that email but has yet to reply. It would be awesome if Global Elements wants to take this off my plate. The visual design and application of legal annotation to price lock-ups that still needs to be solutioned.

**Comment by brianlam1** [comment]
Hello!

Late to the party, but want to shine a light to what and what, not GE Team owns.

As per discussions with Director's last year, Global Elements as a team primarily only anything that touches the Navigation of the site (Header, Footer, Sub, Inpage, Side, Breadcrumbs navigation, etc.) and site search (arguably a form of navigation into itself).

T&Cs (also the first time I recall hearing about it), is not owned by the Global Elements team. Not sure where that came from.

**Comment by DougTelus** [comment]
Is T&C component a TDS owned system feature?

**Comment by varunj90** [comment]
yes @DougTelus it will be a TDS core component

**Comment by gkychow** [comment]
@DougTelus - I agree with @Berjesty. V1 for mobile feels less intrusive than V2. 

For the visuals, we should probably see if the "+/-" makes the most sense and whether there are other options on blending it with the footer a bit better. Is Steph going to be the one doing the visuals? I can work with her once the interactions are approved :)

**Comment by twirlingsky** [comment]
In HS we have a sticky summary at the bottom. So we won't be able to align with any sticky T&C components. 
![screen shot 2019-02-12 at 13 29 14](https://user-images.githubusercontent.com/22402633/52669174-48227500-2eca-11e9-80ff-8952458336d0.png)
![screen shot 2019-02-12 at 13 29 35](https://user-images.githubusercontent.com/22402633/52669180-49ec3880-2eca-11e9-911b-38d8b11789bf.png)

**Comment by DougTelus** [comment]
### **Update**

- added pricing lockup annotation concept
- updated the 'X Close' pattern in legal modals

**Comment by twirlingsky** [comment]
A suggestion: close X (lower case on the close and X in the far right)
(This is the pattern we've been using...)

Also to add a comma between legal #s (eg. 1, 2, 3, 4...)

**Comment by DougTelus** [comment]
> A suggestion: close X (lower case on the close and X in the far right)
> (This is the pattern we've been using...)
> 
> Also to add a comma between legal #s (eg. 1, 2, 3, 4...)

TY, Great suggestions. Made the updates.

**Comment by varunj90** [comment]
core team is taking ownership for this component

cc: @Christina-Lo

**Comment by varunj90** [comment]
Even though the core team is building this component - changing type to discussion so Doug gets credit for all the great design research he did

**Comment by varunj90** [comment]
Terms and conditions is released.

Docs: https://tds.telus.com/components/index.html#terms-and-conditions
