### ISSUE TITLE
Add an optional CTA to PreviewCard

### ISSUE THREAD

**Issue by sketchidea** [telus/tds-community#234]
## Problem statement

- As a developer , I would like to add a CTA link to Preview Card , so that I can use PreviewCard in my SIteBuilder block.

## Recommendation

- Add a chevron link to PreviewCard so that we can use PreviewCard in our SiteBuilder block. Otherwise we will have to build a custom card and won't be able to use the TDS component. This would not be so good for maintenance and consistency.

- Also update the animation effect so that it is triggered by hovering on the whole card, not just the image.

## Design intent

Use case (an example):
"The CTA is included to reinforce that the card is clickable and 'view story' sets the expectation for when they click/tap - that they will be taken to a full story view."

  Describe the value of the new feature from the customer's POV.

  As a customer
  I want to know that the card is clickable
  So that I know there is content to interact with

  Narrative

 Currently the preview card does not include a CTA link, which means that as a customer I have to do a bit of guess work around whether I can click on the card (I have to hover in order to know that its clickable, which is not something I can do on mobile either).

(This space is intentionally left blank. The motivation and design intent go here.)

## Designs

![xl_PureFibre_stories_hover](https://user-images.githubusercontent.com/3803746/59294654-cd2e5880-8c36-11e9-92d7-ce463c5127d4.png)

## Acceptance criteria

The CTA should be a TDS link component. It should be accessible and be able to support inputs including parameters and hashes in case the CTA points to a function rather than a new page.

  DO NOT REMOVE THIS SECTION

  Things to consider when writing acceptance criteria (ACs):

  Things to think about:

  -> What needs to be done to make this accessible?
  -> Visual properties
  -> Interactions
  -> Documentation
  -> Considerations if changes need to be mirrored to tds-core and tds-community
  -> Are there any responsive behaviours or visual differences?
  -> French considerations, do symbols or text need to be rendered in a certain order or manner?
  -> Text considerations, do we need SVGs, symbols, superscript text, or other special formatting?
  -> Make sure the ACs do not overly specify names of props. Try to stay generic and descriptive. Describe the interactions and behaviours of your component.

  Given I am displaying the preview card component
  When I supply a CTA endpoint / hash or query parameter
  Then the component should render a chevron link.

-->

This section is intentionally left blank. See [story writing process](https://github.com/telus/tds-community/blob/master/guide/Community_Backlog.md#5-story-writing).

### User stories

(This section is intentionally left blank. User stories and acceptance criteria go here.)

**Example:**

Scenario: Displaying the component

Given text is provided
Then the text is displayed as a child
And the text size matches core-text `medium`

### Out of scope

(This section is intentionally left blank. Features or items that were deliberately left out of scope during design intent or may be mistaken as within scope are noted here. Link to related issues if possible.)

## Meta

- Include component name and version: vX.Y.Z
- Willing to design solution: Yes/No
- Willing to develop solution: Yes/No
- Has workaround: Yes/No
- Do any similar components already exist in TDS (core or community): Yes/No (link)
- Which teams/applications do you think would use this improvement?
- High impact: Yes/No

**Comment by philroberto** [comment]
@sketchidea Could you include the need to change the "animate" not just on image hover (current state) but when the card is being hovered over as well?

**Comment by varunj90** [comment]
@sketchidea can you ask Kim to add the invision link for the designs

**Comment by nicmak** [comment]
Ok

**Comment by varunj90** [comment]
this is now being QA'ed by @bnadeem-telus 

once Kim attaches designs we will have a designer QA invision

**Comment by bnadeem-telus** [comment]
This has been tested and looks good.

**Comment by varunj90** [comment]
Summary for closing the issue

For future pattern proofing and based on our conversations with CX and content - we have decided not to go ahead with this enhancement: ” the interaction within an interaction is not recommended” and preview card stays as is.
