### ISSUE TITLE
new: price lockup

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#25]
## Problem Statement

As a customer i would like to see the price displayed in a similar format between pages so i can understand what ill paying at a glance

Exists as a story on the TDS core Jira board:
https://telusdigital.atlassian.net/browse/TDS-909

## Recommendation

- text above price w/icon; offer, sale
- text below price; savings, regular price

## Designs

* Screenshots
* Sketch file

## Meta

* Willing to design solution: No
* Willing to develop solution: No
* Has workaround: No
* Do any similar components already exist: No
* Does this pattern exist already but isn’t a community component? (include url) 
All over site

* Which teams/applications do you think would use this improvement?
All teams

* High impact: Yes

**Comment by sketchidea** [comment]
Question for the design team: @twirlingsky @DougTelus @lucylist 
Look at the various permutations of the design lock up that is used across the site, and assess how we can build/design a new component that fits all product requirements.

**Comment by lucylist** [comment]
hey @sketchidea yeah, we have done this. @gkychow did some exploration during the gift of time and we've solidified them down to a few options that can be reused in different use cases. will update this ticket with mocks.

**Comment by lucylist** [comment]
here's the file and screenshots of the designs
<img width="1306" alt="screen shot 2018-08-20 at 12 15 02 pm" src="https://user-images.githubusercontent.com/17018330/44352554-b7b32c80-a472-11e8-9eee-5f1d2d16216f.png">

**Comment by varunj90** [comment]
tds core team (@jraff ) will take on its development: https://telusdigital.atlassian.net/browse/TDS-909

**Comment by marshjr** [comment]
Mobility lockups:

<img width="248" alt="screen shot 2018-08-29 at 10 56 28 am" src="https://user-images.githubusercontent.com/42357996/44796445-03548d00-ab7b-11e8-9837-5c36309a3c48.png">
<img width="536" alt="screen shot 2018-08-29 at 10 56 52 am" src="https://user-images.githubusercontent.com/42357996/44796446-03548d00-ab7b-11e8-9c89-cac65fe3ae9d.png">
<img width="694" alt="screen shot 2018-08-29 at 10 57 09 am" src="https://user-images.githubusercontent.com/42357996/44796447-03ed2380-ab7b-11e8-812b-85cf1aafd497.png">
<img width="688" alt="screen shot 2018-08-29 at 10 57 27 am" src="https://user-images.githubusercontent.com/42357996/44796448-03ed2380-ab7b-11e8-9561-fbff748ff032.png">
<img width="634" alt="screen shot 2018-08-29 at 10 58 33 am" src="https://user-images.githubusercontent.com/42357996/44796449-03ed2380-ab7b-11e8-850a-673312cd3f38.png">
<img width="794" alt="screen shot 2018-08-29 at 10 58 59 am" src="https://user-images.githubusercontent.com/42357996/44796450-03ed2380-ab7b-11e8-8e3c-b2becb645cae.png">
<img width="688" alt="screen shot 2018-08-29 at 11 00 34 am" src="https://user-images.githubusercontent.com/42357996/44796452-03ed2380-ab7b-11e8-95f1-341ccb24280d.png">

**Comment by lucylist** [comment]
@gkychow will be mocking the price lock ups in french so we can make sure it's consistent and works all around.

**Comment by allynoormohamed** [comment]
Home Solutions switched over from “$x/month thereafter” to “$x/month after x months” as “thereafter” tested poorly in the past. Users were often confused as to what this meant. I have asked Tiffany and Laurel to dig up the research. 

But can we consider changing this specific copy? 

Are abbreviations such as "Reg" supported in other non-English languages that we plan to support in the future, and work with accessibility guidelines? 

![screenshot 2018-08-29 14 16 50](https://user-images.githubusercontent.com/42819701/44816159-43753900-ab96-11e8-83a2-be2ce6553652.png)
![screenshot 2018-08-29 14 17 13](https://user-images.githubusercontent.com/42819701/44816160-440dcf80-ab96-11e8-9227-a7515241cb18.png)

**Comment by DougTelus** [comment]
@allynoormohamed Good call outs. The hemingway app puts the word 'thereafter' at a post-graduate reading level. We usually aim to be grade 8 and lower.

With regards to the word 'Regular', business has typically said 'Retail' instead. Retail price.

**Comment by allynoormohamed** [comment]
@DougTelus Good to know. Thanks.

**Comment by DougTelus** [comment]
Do marketing numbers/prices not associated with products fall into this price lockup standards?

See: https://github.com/telus/tds-community/issues/104
Specific ask is around the purple H1 not being appropriate in this use case.
This specific H1 lockup is not represented in our price variations.

**Comment by lucylist** [comment]
for the price lock up component, we're just looking at the individual elements as opposed to the actual content within those elements.. so you guys will be able to put whatever you want..

**Comment by theetrain** [comment]
Update: @nicmak is developing this component for tds-core.

**Comment by varunj90** [comment]
documentation can be found here: https://tds.telus.com/components/index.html#pricelockup
