### ISSUE TITLE
Paragraph text : Text wrapping

### ISSUE THREAD

**Issue by philroberto** [telus/tds-community#250]
## Problem statement

- As a visitor, I would like to see paragraph text leverage more of the available view-port, so that I can scroll less while reading

## Recommendation

-  add text wrapping as feature to existing text paragraph component

## Design intent

The ability to surround a picture or diagram with text (wrapping it) so that it will fit in the available width of a page, window or other display area.

## Designs

example: https://codepen.io/jraff/pen/bPXLxJ
missing contextual deisgn example, though more of a capability.

## Acceptance criteria

This section is intentionally left blank. See [story writing process](https://github.com/telus/tds-community/blob/master/guide/Community_Backlog.md#5-story-writing).

### User stories

(This section is intentionally left blank. User stories and acceptance criteria go here.)

**Example:**

Scenario: Displaying the component

Given text is provided
Then the text is displayed as a child
And the text size matches core-text `medium`

### Out of scope

(This section is intentionally left blank. Features or items that were deliberately left out of scope during design intent or may be mistaken as within scope are noted here. Link to related issues if possible.)

## Meta

- Include component name and version: vX.Y.Z
- Willing to design solution: Yes
- Willing to develop solution: Yes
- Has workaround: No
- Do any similar components already exist in TDS (core or community): No
- Which teams/applications do you think would use this improvement? Universal (specifically About TELUS / Annual report)
- High impact: Yes

**Comment by varunj90** [comment]
Discussion

- 570px is min width for columns for text
- Sticking to single column text 
- Is there user feedback on saying that it’s not the best experience? Or is this coming from creative exploration to want to do this?
- Steven: Reasoning for having text wrap is to have continuity with text and image
- 

Based on our discussion at DPA, we will not be going ahead with text wrapping.

Next steps: @AnishaRawat to set up a time with @philroberto , @Franimal604 and @DougTelus to find creative solutions to visualize massive copy asks.

**Comment by varunj90** [comment]
Closing this issue based on the direction and design exploration can happen on the side.
