### ISSUE TITLE
Comparison cards - variation with a tab

### ISSUE THREAD

**Issue by twirlingsky** [telus/tds-community#253]
## Problem statement

as a customer, I would like to clearly see which plans is the best value or most popular so that I can easily make my purchase decision

## Recommendation

Adding a tab that supports a value prop statement (such as Most popular or Best value) as a variation to the plan cards

## Designs

See the compare card plan as seen here:  
![Screen Shot 2019-07-22 at 2 59 56 PM](https://user-images.githubusercontent.com/22402633/61668401-67030f80-ac91-11e9-9294-a50fbeff9981.png)

https://telus.invisionapp.com/d/main#/console/17553495/369240081/preview

This is an adaptation of the current Most popular flagged channel cards in Home Solutions.
https://www.telus.com/en/shop/home/pik/channels
(there is a fix to put the shadow behind the colour tab)

For compare cards the tab should be limited to a background colour of Telus purple (#4B286D) with white medium weight 16 px font. (a11y)

## Acceptance criteria

This section is intentionally left blank. See [story writing process](https://github.com/telus/tds-community/blob/master/guide/Community_Backlog.md#5-story-writing).

### User stories

(This section is intentionally left blank. User stories and acceptance criteria go here.)

**Example:**

Scenario: Displaying the component

Given text is provided
Then the text is displayed as a child
And the text size matches core-text `medium`

### Out of scope

(This section is intentionally left blank. Features or items that were deliberately left out of scope during design intent or may be mistaken as within scope are noted here. Link to related issues if possible.)

## Meta

- Include component name and version: vX.Y.Z
- Willing to design solution: Yes
- Willing to develop solution: Yes - Home solutions / catalogue team can contribute
- Has workaround: Yes/No
- Do any similar components already exist in TDS (core or community): variation to the compare cards in TDS community
- Which teams/applications do you think would use this improvement?
Home Solutions
Mobility
My Telus
- High impact: Yes

**Comment by twirlingsky** [comment]
Since new brand colours for digital have been approved we'd like to move the tab colour to #7C53A5 which will help distinguish it from the term ribbon (and optically appear a bit set back) 

Will upload revised example shortly

**Comment by twirlingsky** [comment]
HS Research and Learn example for site builder (WIP - Rena is still working on this):
https://telus.invisionapp.com/share/J2T3JAU9ZD6#/screens

**Comment by Christina-Lo** [comment]
hello @twirlingsky! TDS (@donnavitan and I) and CX (@gkychow and @kittybourne) had a chat about this and we have the following feedback. 

There are a few concerns over adding another visual call-out pattern; what are the benefits in having the varying visual cue? When tab is used with a ribbon, are there too many things being called out. Additionally, needing to have a user recall from different sections or pages to connect the dots is perhaps an experience we want to test for before pushing the design into production.

We understand that a solution is required soon, so a suggestion we have regarding the designs shared here https://www.telus.com/en/shop/home/internet/plans?refinements%5BTerm%5D=24&linktype=ge-meganav is grouping the "3-5 year terms" and “bundle and save” details and have them written into the information above before introducing the comparison card. This way, the visual call out of "most popular" can utilize the ribbon.  

Action items:
- @gkychow to connect and work a bit more on how the tab variation is used on a comparison card vs. channel cars
  - Implementation of comparison card tab variation should be restricted to 1 on a page/section
- guidelines to aid with consistent ribbon use
  - Utilize ribbon for most popular 
  - Ribbon used to call out specific offers/gifts/bundles and not just as a visual labeller of common items like terms
- enhance ribbon to allow for more colours/variants to help different levels of visual aid

**Comment by twirlingsky** [comment]
I'd prefer to not revise the comparison cards from their approved state right now. I'd like to do that as we get more into HSC 3.0 (coming soon!) as there will be new requirements. 

The ribbon use for term length was a marketing solve and has proven useful with customers thus far. Having the ribbon float above the card has been seen as disconnected. I noted that in the criteria use for it.

We need to ensure that term length is visible on the card in unfiltered states. And the light purple area is reserved for online discount messages. (Smart Home security is editing their card at the moment down to 3-4 lines max)

With filtering, we can't ever guarantee that a tabbed card will only be 1 per page. 

Happy to table the ribbon discussion evolvement to a separate ticket – the aim of this ticket is for a variation to the cards to add on a new marketing option.

HS research and learn will start building their SHS page on Thursday, July 24, hence the urgency to get this approved for Site builder use. I suspect their other option is to go ahead without the tab and just use the compare cards as-is and dropping the "popular" tab (and avoiding a double ribbon above and inside).
 
In context (Rena is shifting the cards to the left and getting rid of the double outline)
https://telus.invisionapp.com/d/main#/console/17782770/373633428/preview
![Screen Shot 2019-07-23 at 14 16 27](https://user-images.githubusercontent.com/22402633/61748198-8fa00d80-ad54-11e9-9319-682b4b13c850.png)

**Comment by twirlingsky** [comment]
Closing this ticket as we've found a (not ideal) solution for Smart Home Security at aligns with their deadline.

We will revisit the comparison cards and the tab in the future.
