### ISSUE TITLE
new: hero image + wave

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#27]
## Problem Statement

As a designer id like to have a consistent hero image and wave component so that the experience clicking between pages doesn't jump around

## Recommendation

Pick one size for xl,lg,md,sm and codify it

## Designs
not sure if this is right @lucylist ?
![screen shot 2018-06-06 at 7 14 31 pm](https://user-images.githubusercontent.com/9420407/41054160-df4f3f58-69bd-11e8-8ffe-526a195dc4e8.png)

## Meta

* Willing to design solution: No
* Willing to develop solution: No
* Has workaround: No
* Do any similar components already exist: No
* Does this pattern exist already but isn’t a community component? (include url) 
https://www.telus.com/en/bc/internet/content/bundles?linktype=subnav

* Which teams/applications do you think would use this improvement?
B2B
Home solutions
Mobility
* High impact: No

**Comment by sketchidea** [comment]
@jackreeves this exists already in SiteBuilder as a component. The issue with pages having an inconsistent experience, is more around legacy tech stacks. So, the solution would be to move all marketing pages to SiteBuilder which is what we are in the process of doing.
