### ISSUE TITLE
TB: New expandable sticky footer

### ISSUE THREAD

**Issue by lynnepeacock** [telus/tds-community#272]
## Problem Statement

- As a _ , I would like to _ , so that I can \_

## Recommendation

- Description of the proposed solution

## Design intent

(This space is intentionally left blank. The motivation and design intent go here.)

## Designs

**Closed - current plan**
![image](https://user-images.githubusercontent.com/41124620/63799392-068f6f80-c8da-11e9-887f-1c1c05877998.png)

**Closed - new plan**
![image](https://user-images.githubusercontent.com/41124620/63799517-3fc7df80-c8da-11e9-8359-4d33c75d7c9a.png)

**Open - new plan**

![image](https://user-images.githubusercontent.com/41124620/63799475-30e12d00-c8da-11e9-98c7-03cd9d238b46.png)

**InVision links:** 
Open: https://telus.invisionapp.com/d/main/#/console/16902327/365756597/preview
Closed: https://telus.invisionapp.com/d/main/#/console/16902327/378135577/preview

## Acceptance criteria

This section is intentionally left blank. See [story writing process](https://github.com/telus/tds-community/blob/master/guide/Community_Backlog.md#5-story-writing).

### User stories

(This section is intentionally left blank. User stories and acceptance criteria go here.)

**Example:**

Scenario: Displaying the component

Given text is provided
Then the text is displayed as a child
And the text size matches core-text `medium`

### Out of scope

(This section is intentionally left blank. Features or items that were deliberately left out of scope during design intent or may be mistaken as within scope are noted here. Link to related issues if possible.)

## Meta

- Willing to design solution: Yes/No
- Willing to develop solution: Yes/No
- Has workaround: Yes/No
- Do any similar components already exist in TDS (core or community): Yes/No
- Does this pattern exist already but isn’t a community component? (include url)
- Which teams/applications do you think would use this improvement?
- High impact: Yes/No

**Comment by Christina-Lo** [comment]
Meeting notes:
- this specifically allows for someone to compare and view details before they complete all tasks to get to the summary page
- Accessibility considerations: potentially have live region to read out the price changes
- sticky and modals are tricky and they're super inaccessible
- the tongue text would also be tricky to implement

Action items:
- to be aligned with purple top sticky config summary drawer and built as one component with variations (@lynnepeacock @stu-brown)
- look into the reading order and whether or not they are live regions?

**Comment by varunj90** [comment]
hey @lynnepeacock @Stu-Brown have you connected on this yet?

please keep the github ticket updated, thanks!

**Comment by varunj90** [comment]
@twirlingsky will need this for home solutions (NSE: new shopping experience)

@lynnepeacock @twirlingsky @DougTelus please collaborate on the sticky footer.

**Comment by Christina-Lo** [comment]
This ticket is being amalgamated into the summary bar ticket https://github.com/telus/tds-community/issues/204 and will be all solved there
