### ISSUE TITLE
new: loop qual

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#33]
## Problem Statement

As a customer i would like to enter my address once and not have to do it repeatedly,

as a designer i would like a stock standard way to add address qualification to my pages

as a developer i would like to not have to build this complex item over and over again

## Recommendation

Should not contain buisness logic but the form entry component should be the same design between sections.

May need two executions one that is a full width component, other which is an in page component?

## Designs

![screen shot 2018-06-08 at 6 26 45 pm](https://user-images.githubusercontent.com/9420407/41169513-86905a36-6b49-11e8-9a69-760e2ad00430.png)
![screen shot 2018-06-08 at 6 27 09 pm](https://user-images.githubusercontent.com/9420407/41169537-9e76a02e-6b49-11e8-8d15-14274b452325.png)

## Meta

* Willing to design solution: No
* Willing to develop solution: No
* Has workaround: No
* Do any similar components already exist: No
* Does this pattern exist already but isn’t a community component?
https://www.telus.com/en/bc/internet/content/overview?linktype=nav
* Which teams/applications do you think would use this improvement?
home solutions and b2b
* High impact: No

**Comment by ahmadnassri** [comment]
I don't see this addressed as an individual component level, but rather part of customer identity and APIs.

**Comment by sketchidea** [comment]
@jackreeves the eligibility team is building a component to replace this and will be used across all Home Solution pages to ensure consistency
