### ISSUE TITLE
new: filters / pilters

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#34]
## Problem Statement

As a customer i would like to be able to clcick a filter and toggle between content

as a customer i would like to see what has been filtered so that i can decide to view more or filter more

## Recommendation

Decide if we like pilters at https://www.telus.com/en/bc/mobility/phones?linktype=nav
and solve for this scenario:

![screen shot 2018-06-08 at 6 32 55 pm](https://user-images.githubusercontent.com/9420407/41169810-6674abde-6b4a-11e8-8c1d-1b2a60dacae3.png)

Also i would like to see the option of selecting multiple options.

## Designs

![screen shot 2018-06-08 at 6 32 42 pm](https://user-images.githubusercontent.com/9420407/41169815-6bd35648-6b4a-11e8-9adb-77ea7dd5e7d3.png)

## Meta

* Willing to design solution: No
* Willing to develop solution: No
* Has workaround: No
* Do any similar components already exist: No
* Does this pattern exist already but isn’t a community component? (include url) 
https://www.telus.com/en/bc/mobility/accessories/category/phone-and-tablet-cases?linktype=accessories_nav
* Which teams/applications do you think would use this improvement?
Mobility, HS and B2b
* High impact: No

**Comment by varunj90** [comment]
Closing due to duplicate: #189
