### ISSUE TITLE
Pagination: DSM symbol broken

### ISSUE THREAD

**Issue by Christina-Lo** [telus/tds-community#355]
## Description

The DSM component for pagination is broken; the appropriate text styles aren't applied and the Chevron icon is the wrong colour

## Reproduction Steps
Open TDS-Community DSM library, drag and drop the Pagination component onto your Sketch artboard

## Recommendation

 

- Your recommendation here

Apply/create the appropriate text styles and icons for the chevron

- TDS version (npm or DSM): Shared draft
- Willing to develop solution: No
- Has workaround: Yes (breaking out of all the symbols)
- High impact: No

## Screenshots

- Include any relevant screenshots
![Screen Shot 2020-05-06 at 4 03 21 PM](https://user-images.githubusercontent.com/42220619/81222931-215ecb80-8fb3-11ea-97aa-216f2843aa97.png)

**Comment by billtelus** [comment]
Find the right documentation for this component here  https://designsystem.telus.com/community/index.html#pagination.
This issue is no more relevant.
