### ISSUE TITLE
new: product catalogue component

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#36]
## Problem Statement

As a customer i would like product catalogues to look and feel the same so that i can easily navigate.

As a customer i would like product catalogue pages to have filtering options so that i can clear the clutter and focus on what i want.

as a customer i would like to be able to sort products in a catalogue so that i can see the most expensive or popular

As a designer i would like a component that has options for generating a product catalogue page so that we can all use the same.

## Recommendation

Bring in mobility catalogue page and then look at right columns for filtering later.

## Designs
https://www.telus.com/en/bc/mobility/phones?linktype=nav

OR

https://www.telus.com/en/bc/mobility/accessories/category/tech-accessory-sales?linktype=accessories_nav

## Meta

* Willing to design solution: No
* Willing to develop solution: No
* Has workaround: No
* Do any similar components already exist: No
* Does this pattern exist already but isn’t a community component? (include url) 
https://www.telus.com/en/bc/mobility/accessories/category/tech-accessory-sales?linktype=accessories_nav
* Which teams/applications do you think would use this improvement?
* High impact: Yes/No

**Comment by theetrain** [comment]
A product catalogue is not sufficiently granular to necessitate a component. We could instead consider a single product listing as a component if it is sufficiently reusable across all our product teams, such as a product listing:

![image](https://user-images.githubusercontent.com/12798751/44280986-5ac23700-a224-11e8-815e-d6caaa210a11.png)
