### ISSUE TITLE
new: Promo/flag/ribbon/special marker

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#48]
## Problem Statement

as a customer i would like a clear way of seeing if something is on sale or a special feature or new so that i can focus my attention

as a designer i would like a way for all teams to consistently approach flags so that we can improve user experience

## Acceptance Criteria:

- Ribbon should have margin of 16px above and below.
- Should have inner padding of 8px top and bottom.
- The ribbon should expand and contract to fit the inputted text.
- Any text should be allowed as an input / prop, but should be limited to strings only.
- There should only be one line of text allowed, must not wrap to two lines.
- The minimum total width of the ribbon is 126px.

## Recommendation

* Description of the proposed solution

## Designs

![screen shot 2018-06-14 at 3 18 05 pm](https://user-images.githubusercontent.com/9420407/41414450-58a56e08-6fe6-11e8-919f-a334594f7aef.png)
![screen shot 2018-06-14 at 3 17 45 pm](https://user-images.githubusercontent.com/9420407/41414451-58ccf43c-6fe6-11e8-934a-fa63b30a421c.png)

## Meta

* Willing to design solution: No
* Willing to develop solution: No
* Has workaround: No
* Do any similar components already exist: No
* Does this pattern exist already but isn’t a community component?
https://www.telus.com/en/bc/mobility/phones/?linktype=nav
* Which teams/applications do you think would use this improvement?
MOB/HS/B2B
* High impact: No

**Comment by sketchidea** [comment]
Our team (HS R+L) will be building this component as we have a requirement for it in our current sprint.

**Comment by twirlingsky** [comment]
Ribbon:

Usage criteria: for use on a product card to signify a term length contract on an offer (e.g. 2 year term)

![screen shot 2019-02-25 at 10 13 17 am](https://user-images.githubusercontent.com/22402633/53359308-6b481e00-38e7-11e9-8069-160353a9f70f.png)
![screen shot 2019-02-25 at 10 23 21 am](https://user-images.githubusercontent.com/22402633/53359310-6d11e180-38e7-11e9-9e31-d6da62d831e6.png)

**Comment by varunj90** [comment]
@sketchidea are you/ your team still planning to develop this component?

**Comment by nicmak** [comment]
Hi Everyone, our designer Francisco has new designs @twirlingsky 
![ribbons](https://user-images.githubusercontent.com/22725151/55037793-21cd1a80-4fdc-11e9-8a0f-6d6381d71f92.jpg)

**Comment by donnavitan** [comment]
Connected with Francisco regarding "ribbon".

Please review the following file: https://invis.io/a/HJ5CGILLKWQT
Please make sure that you sync/update the file here: https://telus.invisionapp.com/d/main#/projects/prototypes/13362811/assets

I've done the following:
- Height: 32px
- Minimum Width: 131px
- Updated typography rules (it should align with existing text/medium/* styles (but now available in medium and inverted/white)
- 16px at 24px line-height
- Left aligned
- It has a left padding of 16px
- It has a right padding of 24px (including the 8px of tail)
- Vertically centered visually (inspect Invision for reference) https://telus.invisionapp.com/share/5TRB1UFAD4U
- Created it as a symbol so all you have to do is override the label
- Will automagically expand (Anima plugin required)

Next steps:
- Review as necessary
- Add "ribbon" symbol to the TDS Community DSM library under "Components (not coded)"
- Confirm design/dev

**Comment by donnavitan** [comment]
Oh! If it's released in code, then:
* Add "ribbon" symbol to the TDS Community DSM library under "Components (coded)"

**Comment by donnavitan** [comment]
Hello folks, as per my discussion with Francisco, I've added the ribbon component in TDS Community DSM library under "Components (not coded)". When dev is completed, we can move to "Components (coded)". Cheerios!

**Comment by sketchidea** [comment]
Acceptance criteria added

**Comment by nicmak** [comment]
Starting Development today

**Comment by donnavitan** [comment]
Adding notes for reference:
* Minor update was made to the Sketch component to make it shorter in height, now at 24px as per @twirlingsky 
* I'll be updating it as per design QA checklist: http://bit.ly/TDSCommunityDesignChecklist

**Comment by donnavitan** [comment]
@twirlingsky Could you confirm if the left padding should be changed to 8px or keep 16px? Did you want to keep the 24px right padding? Did you want to keep a minimum width or just have the ribbon background expand to whatever the label is?

**Comment by twirlingsky** [comment]
I just gave it a double check and posted a new symbol to DSM. 

Padding left: 8px
Padding right: 16 + 8px - 24 px to allow for the ribbon tail
Padding top and bottom: 4px
Minimum width of 126px is still on - the background can expand to whatever the label is

**Comment by donnavitan** [comment]
Hello all,

As per @twirlingsky's confirmation, here's an updated specs and examples:

### Details
* Height: 24px
* Minimum Width: 126px
* Font: Helvetica Neue
* Font-size: 16px
* Line-height: 16px
* Weight: Medium (aka bold)
* Align: Left
* Colour: White #FFFFFF (aka inverted)
* Vertically centered visually (inspect Invision for reference) 
* Left padding: 16px
* Right padding: 24px (including 8px of ribbon tail)
* Top margin: 8px
* Bottom margin: 8px

### Sketch use
* Use override panel to edit the label
* Will automagically expand (Anima plugin required)

![image](https://user-images.githubusercontent.com/21316148/59217379-ce567b80-8b8b-11e9-8b06-6dada9748e18.png)

https://telus.invisionapp.com/share/5TRB1UFAD4U

**Comment by donnavitan** [comment]
Please note that the latest working file for this is: https://invis.io/a/HJ5CGILLKWQT

**Comment by donnavitan** [comment]
* Confirmed design with @twirlingsky
* Will address if dev is affected with @theetrain

**Comment by mejsullivan** [comment]
Are their docs to see what's been done for accessibility? Saw this was getting released! Exciting!

**Comment by donnavitan** [comment]
@mejsullivan Thank you for bring that up. Reaching out to you and @twirlingsky for additional context where applicable.

It's not an interactive element, but it is a visual callout - so maybe there is an opportunity to enhance the a11y experience. Unfortunately, the use is so free form that it's not limited to "sale", "offer", or "program". Maybe, the only addition is to include such term in the ribbon label?

Please advise and recommend, if folks have suggestions.

**Comment by donnavitan** [comment]
Just adding a note here that design a11y review has been double checked. While the opportunity to enhance the component by providing more meaningful context can be an enhancement; to be considered with @twirlingsky and design direction/CX.

**Comment by varunj90** [comment]
Docs: https://tds.telus.com/community/index.html#ribbon
DSM: tds_community v.1.0.21
Release notes: https://github.com/telus/tds-community/releases/tag/%40tds%2Fcommunity-ribbon%401.0.0
npm: https://www.npmjs.com/package/@tds/community-ribbon

**Comment by mejsullivan** [comment]
@varunj90 @donnavitan - sorry I don't understand what was said above. Is it accessible? y/n?

**Comment by donnavitan** [comment]
@mejsullivan Yes, it's accessible! 😃

Just wanted to make a note that there's still a potential to make an accessibility enhancement that will help indicate that the ribbon is a special feature/offer/discount.

**Comment by mejsullivan** [comment]
Is that what the visual (the shape) is trying to tell people? Or does the text in the ribbon provide that content?
