### ISSUE TITLE
new: Storage selector

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#53]
## Problem Statement

as a designer i would like a consistent way to impliment storage selection for the customer

## Recommendation

None

## Designs

![screen shot 2018-06-14 at 3 51 43 pm](https://user-images.githubusercontent.com/9420407/41416321-da503b28-6fea-11e8-95b2-88031c780977.png)

## Meta

* Willing to design solution: No
* Willing to develop solution: No
* Has workaround: No
* Do any similar components already exist: No
* Does this pattern exist already but isn’t a community component? (include url) 
https://www.telus.com/en/bc/mobility/phones/iphone-x?linktype=nav
* Which teams/applications do you think would use this improvement?
B2B MOB
* High impact: No

**Comment by theetrain** [comment]
Storage Selection is a pattern exhibited by the Button Group component. Deduplicating in favour of #57
