### ISSUE TITLE
new: toggle switch

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#55]
## Problem Statement

as a designer i would like a more Skeuomorphic way for customers to toggle on/off states than radio buttons

## Recommendation

might be a core component?

## Designs

* Screenshots
* Sketch file
![image](https://user-images.githubusercontent.com/9420407/41416937-55cdc0d0-6fec-11e8-8b7a-bab6dc6bc906.png)
![image](https://user-images.githubusercontent.com/9420407/41416945-5971aee0-6fec-11e8-9095-506be8261538.png)

## Meta

* Willing to design solution: No
* Willing to develop solution: No
* Has workaround: No
* Do any similar components already exist: No
* Does this pattern exist already but isn’t a community component? (include url) 
* Which teams/applications do you think would use this improvement?
* High impact: No

**Comment by jesdavpet** [comment]
@jackreeves Please see https://github.com/telus/tds-community/issues/29 which has an approved design, and is already being used in production.

**Comment by jesdavpet** [comment]
Closing as a duplicate.

**Comment by jackreeves** [comment]
thanks @jesdavpet ! sorry got an xls backlog from a component jam held a few months ago... didnt see it already
