### ISSUE TITLE
new: reviews

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#56]
## Problem Statement

as a customer i would like to see other customer reviews on the site

as a designer i would like to have a standard way of displaying review information

## Recommendation

Ideas: 

Submit panel
Review panel
Filter/Sort
Verify customer
Top vs worst review
Stars
Was this helpful

## Designs

* Screenshots
* Sketch file
![image](https://user-images.githubusercontent.com/9420407/41417913-eea498c2-6fee-11e8-9fa8-5e5434a29d36.png)
![image](https://user-images.githubusercontent.com/9420407/41417933-fa11171c-6fee-11e8-8397-efcb43dafbd4.png)

## Meta

* Willing to design solution:No
* Willing to develop solution: No
* Has workaround: No
* Do any similar components already exist: No
* Does this pattern exist already but isn’t a community component? 
* Which teams/applications do you think would use this improvement?
MOB / B2B
* High impact: No

**Comment by ahmadnassri** [comment]
another example of a full product category vs. a design component.

**Comment by sketchidea** [comment]
@jackreeves mobility has a review service - bazaar voice, this could be used more extensively.

**Comment by simpleimpulse** [comment]
This is currently not in the scope of a TDS component, closing for now.
