### ISSUE TITLE
new: price summary card

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#58]
## Problem Statement

As a customer i would like to get an overview of what i have selected thus far and see the totals summarised clearly

as a designer i would like to display summary pricing in a card with consistent place and formatting so they dont get confused and clearly understand what they are purchasing 

## Recommendation

Have design jam and see how many different variants we need for entire business. can we rationalize to one?

## Designs

![screen shot 2018-06-15 at 1 39 05 pm](https://user-images.githubusercontent.com/9420407/41466188-7e957a2a-70a1-11e8-8743-e678aa53ecc9.png)
![screen shot 2018-06-15 at 1 37 56 pm](https://user-images.githubusercontent.com/9420407/41466189-7eb46de0-70a1-11e8-85b1-4a51a291bc74.png)
![screen shot 2018-06-15 at 1 36 47 pm](https://user-images.githubusercontent.com/9420407/41466190-7ed14546-70a1-11e8-84ed-100c186a24f8.png)

## Meta

* Willing to design solution: No
* Willing to develop solution: No
* Has workaround: No
* Do any similar components already exist: No
* Does this pattern exist already but isn’t a community component? (include url) 

https://www.telus.com/en/bc/mobility/cart
https://www.telus.com/en/bc/shop/checkout/cart
https://www.telus.com/en/bc/mobility/planbuilder?INTCMP=Tcom_Plans_Individual_Plans_BAN_Plan_Builder&linktype=plans

* Which teams/applications do you think would use this improvement?
B2B HS MOB
* High impact: No

**Comment by philroberto** [comment]
closing because commerce team is working on it.
