### ISSUE TITLE
new: calendar picker

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#60]
## Problem Statement

As a customer I need the ability to view time and date availability to select a single installation appointment for a technician to come and install a TELUS product or service at my service address.

## Requirements/Stories

https://telusdigital.atlassian.net/browse/TELCOM-252

https://telusdigital.atlassian.net/browse/TELCOM-253

## Recommendation

- Unified Checkout to contribute a calendar component that teams can consume for the use case of scheduling appointments

- Work with a11y primes to enhance & future-proof designs

- Remain TDS compliant 

- Provide allowable variants & outline the usage for all cases

## Designs
Preview: https://telus.invisionapp.com/d/main#/console/16124092/335215125/preview
Source file (WIP): https://telus.invisionapp.com/d/main#/projects/prototypes/16124092/assets

## Meta

* Willing to design solution: Yes
* Willing to develop solution: Yes
* Has workaround: 
* Do any similar components already exist: Yes
* Does this pattern exist already but isn’t a community component? Yes
* Which teams/applications do you think would use this improvement?
HS, MyTELUS, Business
* High impact: Yes

**Comment by twirlingsky** [comment]
Home Solutions uses a calendar component in their checkout flow to book installation appointments. Attached are screen grabs.
<img width="1046" alt="calendarloading" src="https://user-images.githubusercontent.com/22402633/46174092-f0f26f80-c25c-11e8-8948-fb57684800ab.png">
<img width="1084" alt="calendarnoselection" src="https://user-images.githubusercontent.com/22402633/46174109-01a2e580-c25d-11e8-886b-70d8f77087ab.png">
<img width="1114" alt="calendardateselection" src="https://user-images.githubusercontent.com/22402633/46174113-049dd600-c25d-11e8-806c-726cb3201f77.png">
<img width="1122" alt="calendarselectiondateandtime" src="https://user-images.githubusercontent.com/22402633/46174121-0a93b700-c25d-11e8-8a06-6518e5bd6440.png">

**Comment by varunj90** [comment]
unified commerce is working on this component.

@abansil and @uxjames can you add the design here and link to sketch/dsm

**Comment by abansil** [comment]
in interim here's a screencap:
![screen shot 2018-11-19 at 5 51 01 pm](https://user-images.githubusercontent.com/37587197/48739985-b89b5c00-ec23-11e8-870f-a27b87d0db33.png)
- key difference is visual updates
- a11y & IxD to be outlined/improved

after final review/sign-off @uxjames can provide sketch file. I'll follow up with DSM integration

**Comment by varunj90** [comment]
hey @abansil and @uxjames any updates on the design?

**Comment by uxjames** [comment]
@varunj90 there are no updates at present. The design is done but we would like it reviewed for accessibility. Once this has been completed we will update with final designs incorporating user testing and accessibility considerations.

**Comment by mujtabahasni** [comment]
My squad is also interested in this component. What is the status of this?

**Comment by abansil** [comment]
Will connect with @uxjames next week for the final designs & a11y/testing compilation and can bring up to DPA

**Comment by sbarre** [comment]
Question:  is there a way to jump by year?   

What if we're using this picker to request birth dates or dates that aren't necessarily close to the current date?

**Comment by uxjames** [comment]
We are currently looking at integrating the Airbnb Calendar component. [React Component](https://github.com/airbnb/react-dates) This does not have a year picker. 

For date of birth, I wouldn't use this and would only use it for events that will occur in a shorter period of time, such as an appointment. [Nielsen Norman Group Recommendations](https://www.nngroup.com/articles/date-input/).

Google and Yahoo use a list for months (January 01, February 02 etc) and then have the day and month as input fields. This seems like the best option for date of birth as it avoids a lot of validation issues. Hope this helps.

**Comment by abansil** [comment]
@sbarre

**Comment by abansil** [comment]
**DPA feedback**

- [ ] Caret visual design
- "It should be there", "Good visual representation", "Closer to input field"

- [ ] Is there a date range picker? Between x and y dates
- For MVP the calendar's req is to select 1 date for appointment scheduling
- Calendar is not recommended for DOB use

- [ ] Date picker IxD
- Customer can type into input field (calendar persists)
- Customer can interact with calendar 

- [ ] Visual design/a11y
- Greyed out dates --> changed colours to ensure low visibility users can see dates in widget
- Icons from arrows to chevrons 
- Working with a11y primes + matrix 

@uxjames

**Comment by brianlam1** [comment]
Code was submitted for review as of mid-Feb

PR: https://github.com/telus/tds-community/pull/187

**Comment by Andrew-K-Lam** [comment]
@brianlam1 Hi Brian, I'm confused, what does that PR (https://github.com/telus/tds-community/pull/187) have to do with with a new calendar picker?

**Comment by varunj90** [comment]
hi @abansil and @fzero what is the status on this for design and development?

**Comment by donnavitan** [comment]
As per my discussions with @uxjames, and the latest designs found within TDS community DSM library. We've made updates to make the details further align with TDS text/layer styles, as well as box sizing/spacing while trying to stay as close as to the provided/approved designs.

https://telus.invisionapp.com/dsm/telus/tds-community/folder/components/5c6c4c52038f5f0ac720a712

h2. Out of scope, future design considerations:
* Make inline sizing responsive (not just horizontal stretching)
* Explore date indicator as circle or pill shaped when inline calendar is horizontally stretched
* https://telus.invisionapp.com/dsm/telus/tds-community/asset/components/5ca62c99789f906d2166880a

**Comment by donnavitan** [comment]
Due to recent discussions in TDS support, development might not resume until after June. However, the designs are ready for use in TDS community DSM library under "Components (not coded)" should you want to reference them in your design.

**Comment by varunj90** [comment]
any updates @brianlam1 , @coltonpowershifter : https://github.com/telus/tds-community/pull/181

**Comment by brianlam1** [comment]
Hello!

Unfortunately, Colton is no wonder with Digital. We should have some time next week to update the contribution of the calendar code.

**Comment by varunj90** [comment]
@harmeetsaimbhi @abansil and TDS team (@theetrain @donnavitan) will be working together to get this to completion 

JIRA epic: https://telusdigital.atlassian.net/browse/TDS-1568

**Comment by donnavitan** [comment]
Reviewed with CX the font size of the month and year navigation and will update it to use "Text Medium (16px bold)" for the XS component only. I've gotten @gkychow @kittybourne and @abansil's agreement. I will update the TDS Community DSM accordingly.

**Comment by donnavitan** [comment]
Updated TDS Community DSM: Month and Year now use Text Medium (16px bold) for the XS component only.

**Comment by varunj90** [comment]
This is currently in QA phase by core team

**Comment by marcod1419** [comment]
This component has been released! Thank you all for the effort! The component will be available shortly at this link: https://tds.telus.com/community/index.html#!/DatePicker
