### ISSUE TITLE
new: chat component

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#64]
## Problem Statement

As a customer i would like to chat with support  and know that it is not a phishing site

## Recommendation

TDS styled chat box with icons buttons etc

![screen shot 2018-06-15 at 2 27 33 pm](https://user-images.githubusercontent.com/9420407/41467887-54ae77a0-70a8-11e8-82ee-d7cc6beca60c.png)
![screen shot 2018-06-15 at 2 27 28 pm](https://user-images.githubusercontent.com/9420407/41467888-54d34d0a-70a8-11e8-8059-09e4e3a9d7de.png)

## Designs

![screen shot 2018-06-15 at 2 27 58 pm](https://user-images.githubusercontent.com/9420407/41467886-548dd054-70a8-11e8-8eab-8b49b47db305.png)

## Meta

* Willing to design solution:No
* Willing to develop solution: No
* Has workaround: No
* Do any similar components already exist: No
* Does this pattern exist already but isn’t a community component? (include url) 
https://www.telus.com/en/bc/mobility/planbuilder?numPeople=4&dataPlanSOC=SDSH12GB&voicePlans=PYCUNLP70,PYCUNLP70,PYCUNLP70,PYCUNLP70&needsDevices=false,false,false,false
* Which teams/applications do you think would use this improvement?

MOB/HS/MYACC
* High impact: No

**Comment by sketchidea** [comment]
We have a chat component already, and there is a team that works on chat. Doesn't look like it is suitable to be a TDS community component.
