### ISSUE TITLE
new: language switcher

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#65]
## Problem Statement

As a customer I would like to easily switch my language and region

## Recommendation

Improve the region switcher and create a component

## Designs

FYI designed & developed as a GE component. 

M to XL
https://telus.invisionapp.com/share/KYNN05HXPJT

XS to S
https://telus.invisionapp.com/share/JDO0097T2C5

## Meta

* Willing to design solution: Yes
* Willing to develop solution: Yes
* Has workaround: No
* Do any similar components already exist: No
* Does this pattern exist already but isn’t a community component? No
* Which teams/applications do you think would use this improvement? All outcome teams
* High impact: No

**Comment by varunj90** [comment]
@abansil can you update the ticket with the design once you have it ready.

@lucylist will connect with you on this one

**Comment by abansil** [comment]
@varunj90 @lucylist updated with invision designs. Re-iterating that this will live as a GE component rather than a TDS-community component.

FYI / cc: @brianlam1 @xingbo828 @harmeetsaimbhi

**Comment by brianlam1** [comment]
I suggest this to be closed. Language and region handling should only be handled in the Header and should not be in-application as this should be global settings

**Comment by theetrain** [comment]
Closing due to this being claimed by Global Elements.
