### ISSUE TITLE
new: Breadcrumbs

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#66]
## Problem Statement

As a customer i would like to know what page i am on and in which section im currently located in

as a designer i would like a standard execution of breadcrumbs and placement on the page so that i can easily add it consistently

## Recommendation

![screen shot 2018-06-15 at 2 32 23 pm](https://user-images.githubusercontent.com/9420407/41468054-ef76569a-70a8-11e8-9f74-4f4d31646bfd.png)

Header or footer breadcrumbs?
SEO concerns?

## Designs

* Screenshots
* Sketch file

## Meta

* Willing to design solution: No
* Willing to develop solution: No
* Has workaround: No
* Do any similar components already exist: No
* Does this pattern exist already but isn’t a community component? (include url) 
https://www.telus.com/en/bc/mobility/accessories/category/phone-and-tablet-cases?linktype=accessories_nav
* Which teams/applications do you think would use this improvement?

MY ACC, HS, MOB, b2b
* High impact: Yes/No

**Comment by sketchidea** [comment]
Lets discuss with design leads in Monday's DPA breakout session. Component exists in Core backlog as well.

**Comment by theetrain** [comment]
There are some concerns regarding how breadcrumb links are generated in the various page-generation contexts at TELUS. My proposal is by decoupling the generation logic from the visual appearance of breadcrumbs, we can still make a fully-designed functional component that accepts parameters for all use cases.

For example:

```js

**Comment by theetrain** [comment]
There are some concerns regarding how breadcrumb links are generated in the various page-generation contexts at TELUS. My proposal is to decouple the generation logic from the visual appearance of breadcrumbs. This way, we can still make a fully-designed functional component that accepts parameters for all use cases.

For example:

```jsx
import Breadcrumbs from '@tds/community-breadcrumbs'
import Link from '@tds/core-link'

const linkList = [
  {
    label: 'Home',
    href: '/'
  },
  {
    label: 'Mobility',
    href: '/mobility/'
  },
  {
    label: 'Accessories',
    href: '/mobility/accessories'
  }
] // This can be generated however you like

const App = () => (
  <Breadcrumbs>
    ...linkList.map( link => (
      <Breadcrumbs.Item href={link.href} label={link.label} linkType={<Link />} />
    )
  </Breadcrumbs>
)
```

This example can achieve the design above. It can also accept the `react-router` or `@tds/core-link` component via a `linkType` prop. The parent `<Breadcrumbs>` component could detect when there are multiple children and then insert aesthetic slashes (`/`) between each item, and then not render a hyperlink for the last child element, which should be purple text.

**Comment by agorovyi** [comment]
@theetrain 
Your proposal works great as a highly re-usable component and I'm sure can cover most (if not all) of the use-cases.

The concerns that could be raised I think are not necessarily tight to TDS specifically but more of and organizational ones. For example:

1. How many links are too many in the **Breadcrumbs**?
2. Do we need to limit how many links should be in there and also how long they are supposed to be?
3. Do we want to possibly collapse the middle of the Breadcrumbs component and show it like this if we decide that we can't have too many links:
`
Link 1 / Link 2 ... / Link 5
`

Also, just wanted to throw an example of how it could look like without any limitations:
https://www.toronto.ca/community-people/children-parenting/children-programs-activities/licensed-child-care/toronto-early-learning-and-child-care-services/telccs-centre-locations/

<img width="385" alt="screen shot 2018-09-18 at 3 45 10 pm" src="https://user-images.githubusercontent.com/26413531/45712281-e8fa4780-bb59-11e8-8dbd-b2180090e2a7.png">

**Comment by Christina-Lo** [comment]
TDS Core will be working on this issue. 
https://telusdigital.atlassian.net/browse/TDS-884

**Comment by githubjosh** [comment]
This issue was first raised also raised in [Add Breadcrumbs throughout TELUS.com](https://github.com/telus/seo-guild/issues/11)

**Comment by githubjosh** [comment]
WRT to breadcrumb trail length. 

From a pathing perspective, our [SEO guidelines](https://github.com/telus/reference-architecture/blob/master/testing/nonfunctional/seo.md#url-structure) are to have a "Max of 3 path [parts] excluding language and region parameters".

Still, some URLs currently exceed this and there is no restriction on the length of a path: e.g. `HOME > Business > Mobility > Phones > Super Deluxe Amazing Phone for Hipsters` is a valid use case and breadcrumb trail.

Further, the pathing lengths are subject to change pending the IA work being conducted by Tracey Vanderghem.

[Breadcrumb on Galaxy page](https://www.telus.com/en/bc/mobility/phones/samsung-galaxy-note-9)
![image](https://user-images.githubusercontent.com/224624/46881250-f503bd00-ce18-11e8-9b46-17df5779387e.png)

**Comment by varunj90** [comment]
component released and documentation can be found here: https://tds.telus.com/components/index.html#breadcrumbs
