### ISSUE TITLE
new: Address bar with cart

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#67]
## Problem Statement

As a customer i would like a consistent place to see and change my address

## Recommendation

![screen shot 2018-06-15 at 2 35 52 pm](https://user-images.githubusercontent.com/9420407/41468192-6c23144e-70a9-11e8-8238-810b6b1c4dec.png)

## Designs

https://telus.invisionapp.com/d/main#/console/14046124/293569366/preview

## Meta

* Willing to design solution: No
* Willing to develop solution: No
* Has workaround: No
* Do any similar components already exist: No
* Does this pattern exist already but isn’t a community component? (include url) 
https://telus.invisionapp.com/d/main#/console/14046124/293569366/preview
* Which teams/applications do you think would use this improvement?
* High impact: Yes/No

**Comment by theetrain** [comment]
This appears to be more inline with the goals of Global Elements.

cc @brianlam1
