### ISSUE TITLE
ProgressBar component for displaying usage information

### ISSUE THREAD

**Issue by mujtabahasni** [telus/tds-community#68]
## Problem Statement
As a developer I would like to include a progress bar component so that my app can provide usage 
 and capacity information visually for customers.

 * There is currently no standard progress component in the TDS, although `<progress />` is a standard html5 element.   

 * There exists informal design convention for this component, which is more/less agreed to and being used by at least on other team but its not formally codified in the TDS.  

## Recommendation

* A common component, which can be extension of the HTML <progress /> element  but does follow the design conventions currently being used.

* There already exist a component that is being shared for this purpose: https://github.com/telus/my-account-usage/tree/master/ui/src/components/Common/ProgressBar

## Designs

![image](https://user-images.githubusercontent.com/32303524/41726827-f751d7b2-7540-11e8-972c-b1cac55365d0.png)

## Meta

* Has workaround: Yes
* Do any similar components already exist: Yes
* Does this pattern exist already but isn’t a community component? *Yes*: https://github.com/telus/my-account-usage/tree/master/ui/src/components/Common/ProgressBar
* Which teams/applications: 'My Account / My Telus'
* High impact: No

**Comment by jesdavpet** [comment]
Just want to follow up after a brief conversation with @DineshAlapati and @mujtabahasni this afternoon.

To summarize:
- the atomic `ProgressBar` component will consist of the progress bar only
- intention is **not** to include the labelling text (this can be added in a higher level wrapper component if needed)
- this component is already in production, and the hope is to port that over, then refine subsequent versions as necessary, following any design refinements

@lucylist @Berjesty:
<img width="688" alt="screen shot 2018-06-21 at 2 32 55 pm" src="https://user-images.githubusercontent.com/5464587/41738891-5e38699e-7561-11e8-91c8-b8fd7f90a9d3.png">

**Comment by mujtabahasni** [comment]
Update: 
![image](https://user-images.githubusercontent.com/32303524/41920149-11728a92-792e-11e8-865b-8ce962133126.png)

**Comment by DineshAlapati** [comment]
@jesdavpet, I see the PR for this issue is merged. Does this mean the component is published to NPM registry? Also, I don't see the component in TDS community list, do we need to update anything else?

**Comment by jesdavpet** [comment]
@DineshAlapati @mujtabahasni closing this issue since the component has been published.

Please see:
NPM: `@tds/community-progress`
Docs: https://tds.telus.com/community

Thanks for your work on this!

**Comment by varunj90** [comment]
assignees have been added on closed issue to reflect power level (points) on community heroes board (coming soon!)
