### ISSUE TITLE
<SkeletonProvider /> High-level component for "skeletonizing" TDS components.

### ISSUE THREAD

**Issue by mujtabahasni** [telus/tds-community#88]
## Problem Statement

I have observed that some teams use series if/else or ternary constructs to selectively switch display components with skeletons.   This can sometimes make code appear cluttered and hard to manage.

## Recommendation
I am proposing a simple method to make do this cleaner and offer some sensible presets using the existing TDS Skeleton component. 

* Provide a high-order-component (HOC) for wrapping TDS components and other React elements with a default or a given Skeleton.
* Provide a high-level component e.g <SkeletonProvider></SkeletonProvider> to contain TDS components and orchestrate the transition to-and-from the Skeleton state.

This pattern is current being developed for the Internet Overview page:
https://github.com/telus/my-telus-home-internet

### Defaults for standard TDS components
I also further recommend providing skeletonize defaults for a subset TDS components, including Text, Heading, Box, Image etc.   

This way the <SkeletonProvider /> can wrap this subset of TDS components an minimize the amount of code needed to write add skeleton loading to UIs built with TDS components.

## Designs

This is a simple [StackBlitz demo][1] I did about a month ago: 
[![image](https://user-images.githubusercontent.com/32303524/44405058-63698480-a526-11e8-8334-29793d78ea8e.png)][1]

[1]: https://stackblitz.com/edit/skeleton-hoc?file=index.js

## Meta

* Willing to design solution: Yes
* Willing to develop solution: Yes
* Has workaround: Yes
* Do any similar components already exist in TDS (core or community): No
* Does this pattern exist already but isn’t a community component?  Yes:
  [SkeletonProvder](https://github.com/telus/my-telus-home-internet/tree/master/ui/src/components/Common/SkeletonProvider)
  [TDS Skeleton Defaults](https://github.com/telus/my-telus-home-internet/tree/master/ui/src/components/Common/Skeletons)
* Which teams/applications do you think would use this improvement? All teams.
* High impact: No

**Comment by theetrain** [comment]
Hello, based on our preliminary review, this seems to be an alternative usage of `<Skeleton />`, by wrapping child nodes rather than rendering standalone Skeletons. 

We can try gathering interest from other consumers of Skeleton and then bump the priority higher. Would you consider this an enhancement for `<Skeleton />`, or a new component?

It could be like the following, so that `<Skeleton />` can be used standalone, or as a wrapper:

```jsx
<Skeleton>
  <Text>My content</Text>
</Skeleton>
```

**Comment by varunj90** [comment]
@invalidred to reach out to @mujtabahasni and provide an update regarding Skeleton enhancements

**Comment by mujtabahasni** [comment]
I think we can extend `<Skeleton />` but we may need to add a boolean attribute so that we can enable/disable the skeleton state of the children components.

**Comment by invalidred** [comment]
Spoke with @mujtabahasni about his `<Skeleton />` HOC wrapper and I think it's a pretty cool idea. I think its definitely worth pursuing for 2 reasons. 

1. Consistent way to tackle how we do loading screens using skeletons (a great candidate for TDS recipes)
2. Keeps skeletons in sync with design (currently i've noticed some teams have duplicate skeleton views that shows up while waiting for data and actual view to show data)

To test the idea, what we are going to do is transform an existing Skeleton implementation and port it the new `<Skeleton />` HOC implementation and see how much work is involved and see what's the best way to tackle this issue. We plan on having something by next Fridays DPA meeting.

**Comment by mujtabahasni** [comment]
Here is the propose extension to the <Skeleton />  API for wrapping existing components with skeleton.  

[skeleton docs](https://user-images.githubusercontent.com/32303524/49402022-c1595b00-f716-11e8-8d25-3fc4a9a2c299.png)

**Comment by varunj90** [comment]
hey @mujtabahasni are you going ahead with the development for this? 

next steps? @invalidred

**Comment by mujtabahasni** [comment]
Adding the ability to customize how the skeleton is rendered for a componenet or element by passing a component to the `skeleton` property

![image](https://user-images.githubusercontent.com/32303524/49895022-68c44500-fe1d-11e8-8916-ca0ac8973822.png)

**Comment by mujtabahasni** [comment]
@varunj90 There is currently a branch where work is being done `auto-skeleton-provider`

**Comment by invalidred** [comment]
Next steps for this would be, there are some minor fixes @mujtabahasni needs to make, and then we'll regroup and try to use it on some existing page to iron out other kinks and then once we're confident then we'll push the changes, hopefully. What do you think @mujtabahasni @varunj90 ?

**Comment by invalidred** [comment]
Had a discussion with @mujtabahasni this morning about named export for `SkeletonProvider` in `@tds/community-skeleton` and it would be better to keep `SkeletonProvider` in a separate package

❌  `import Skeleton, {SkeletonProvider} from '@tds/community-skeleton'`
✅  `import SkeletonProvider from '@tds/community-skeleton-provider'` 

The reason being
- The chance of using `SkeletonProvider` and `Skeleton` together is very low, it's going to be either or usage pattern
- Ship less bytes of code to client when only `Skeleton` is used. Tree shaking should alleviate the issue, but you need proper web pack setup to take advantage of it.   
- Conforms to existing TDS patterns of one package per component.

@sketchidea @theetrain i would like to know your thoughts.

**Comment by simpleimpulse** [comment]
@theetrain and @invalidred to collaborate and figure out the impact of changing this component, while TDS transitions to NPM.

**Comment by invalidred** [comment]
UPDATE: 
spent time with @theetrain to update SkeletonProvider branch by rebasing it to use ` npm` and get rid of `yarn`. @theetrain suggested to QA it locally using `npm pack` command. On doing so found `<SkeletonProvider />` uses `shortId` module which uses `cluster` node module which does not work on Front End, thus breaking webpack build.

![screen shot 2019-02-22 at 9 59 35 am](https://user-images.githubusercontent.com/5270458/53250768-15763a80-3689-11e9-933d-5f768da2bb95.png)

The Odd thing is, why did the e2e tests not catch this, as `<SkeletonProvider />` was part of the e2e tests?

![screen shot 2019-02-22 at 9 54 00 am](https://user-images.githubusercontent.com/5270458/53250794-27f07400-3689-11e9-8e34-0b18c9db410e.png)

The following needs to happen
1. TDS Core members to help us understand why e2e tests did not catch the issue above
2. @mujtabahasni to replace `shortId` with `uuid` module to see if this issue is resolved.

**Comment by mujtabahasni** [comment]
@theetrain @invalidred Is there a status update for this issue?    Thanks

**Comment by invalidred** [comment]
Had a meeting with @apurvray to discuss missing Image _square_ shapes in `<Skeleton />` component and he said that from UX/UI perspective we can easily represent that with a _circle_ shape which the `<Skeleton />` component already supports. So there is no value in adding a _square_ or _rectangle_ shape to `<Skeleton />` component. @mujtabahasni was okay not including _square_ shape in `<SkeletonProvider />`.

This leads to 2 discussion points
1. Does anyone object which what @apurvray said about representing images as ONLY _circles_ in skeletonize form ?
2. @mujtabahasni can you confirm if the references to _square_ shape in `<SkeletonProvider />` docs removed?

**Comment by invalidred** [comment]
@mujtabahasni to remove code to support square images and update docs. Once that's done, we'll push it to prod.

**Comment by mujtabahasni** [comment]
In addition to the above, this PR needs to be rebased align with current work.  I expect to continue this work soon.

**Comment by theetrain** [comment]
[@tds/community-skeleton-provider](http://npmjs.com/@tds/community-skeleton-provider) was released on July 19, 2019.
