### ISSUE TITLE
new: Testimonials Card

### ISSUE THREAD

**Issue by joperron** [telus/tds-community#90]
## Problem statement

We need the testimonials card for the Telus Health website we are building with Site Builder. It exists in the Sketch components, but not in the TDS React components apparently.

## Recommendation

* Develop the new card component

## Designs

Attached are screens from DSM and in the context of our project:

![screen shot 2018-08-17 at 1 41 24 pm](https://user-images.githubusercontent.com/1000260/44426569-fae9ca00-a55c-11e8-8a5a-6a7c2d7f4255.png)
![screen shot 2018-08-17 at 1 19 02 pm](https://user-images.githubusercontent.com/1000260/44426561-f3c2bc00-a55c-11e8-97ea-c4207264c3ba.png)

## Meta

* Willing to develop solution: Yes
* Do any similar components already exist in TDS (core or community): [Yes](https://tds.telus.com/components/index.html#card) 
* Which teams/applications do you think would use this improvement? Definitely Telus Health ;)
* High impact: No

**Comment by wascloud** [comment]
DPA Group: Is the request for the entire card? or just the image in a circle?

**Comment by joperron** [comment]
Up to you, would be easier to just do the entire card instead of fragmenting what exists, your call

**Comment by agorovyi** [comment]
@githubjosh @xingbo828 We need your input here. We were discussing TDS `<Image>` Component and that it's missing LazyLoad functionality and were trying to come up with a solution on how to go around this.

There are two proposals that came up in the discussion:

1. Merge `<ResponsiveImage>` Component from [redux-contentful](https://github.com/telus/redux-contentful#responsiveimage-) with TDS `<Image>` Component and have one unified (potentially) TDS Component.
2. Copy over LazyLoad functionality from `<ResponsiveImage>` Component into TDS `<Image>`. However, this approach will duplicate the need for long-term maintenance of LazyLoad functionality in both places.

Could you please provide your thoughts and recommendations on this?

**Comment by githubjosh** [comment]
@agorovyi 

`withLazyLoad.jsx` in `redux-contentful` is just a wrapper (HOC). You could potentially import this into TDS to wrap your images.

Notes: 
- Other than Lazy Loading, the properties available to the ResponsiveImage component are specific to the Contentful Image API: e.g. compression. image sizing, image format, ... 

Alternatively, you could simply import the `react-lazy-load` module and wrap your TDS image component. 

`import LazyLoad from 'react-lazy-load';
...
<LazyLoad>
...
</LazyLoad>
`

From my POV, the tangible benefits of using the existing HOC are:

- alignment on a single Lazy Load package
- ease of maintaining the default Lazy Loading settings of which there is currently one: `offsetBottom` = 400

I'd start with the HOC, but I'm mostly indifferent. The LOE either way is nominal

**Comment by githubjosh** [comment]
@agorovyi 
Alternatively, you could pull `withLazyLoad.jsx` out of `redux-contentful`, move it into TDS, then make this TDS component a dependency of `redux-contentful` for use with `responsiveImage`: i.e. flip the paradigm

**Comment by agorovyi** [comment]
@githubjosh This is it. Like this idea.

**Comment by varunj90** [comment]
@agorovyi will be story writing this!

**Comment by agorovyi** [comment]
### User Story

As a TDS-Community consumer, I want to display a Testimonial Component that will consist of Card, Image, and Paragraph Core Components put together in one standalone Component as per the approved design.

### Acceptance Criteria: Component

- **Given** I am displaying the <Testimonial> component
- **When** I supply it with testimonial text, image, author title, author more info
- **Then** I should see the testimonial text placed at the top within the Card Core Component, then in the next row I should see the circle image placed on the left and title in bold and more info regular text placed on the right from the image<br/><br/>



- **Given** I am displaying the <Testimonial> component
- **When** I supply it with testimonial text, author title, author more info but no image
- **Then** I should see the testimonial text placed at the top within the Card Core Component, then in the next row I should see the title (in bold) and more info (in normal weight) on the next line

### Tech Notes

- Do we need to have an option without the image or image must be a required element?
- What elements must be required in this Component? My suggestion: testimonial text, testimonial author title

**Comment by theetrain** [comment]
>Do we need to have an option without the image or image must be a required element?

Since images are optional, we recommend providing a prop interface that accepts the core-image component.

>What elements must be required in this Component? My suggestion: testimonial text, testimonial author title

Looking at an example, I see (1) paragraph text for the testimonial, (2) bold text for the author, and (3) subtext for the author title are always required.

**Comment by joperron** [comment]
Hey guys,

Just wanted to check in and ask how close we are to starting dev on this, and who is going to do it?

**Comment by agorovyi** [comment]
@joperron I've already submitted a PR (#114) for it. It will most likely have some revisions based on provided feedback as it is my first one here.

**Comment by theetrain** [comment]
Update, we're going to need another pull request to allow the `<Image/>` component to be inserted by the consuming developer, while creating maximum boundaries in the testimonial card so that images do not exceed 60x60px.

**Comment by theetrain** [comment]
This component was released: [@tds/community-testimonial@1.0.0](https://github.com/telus/tds-community/releases/tag/%40tds/community-testimonial%401.0.0)

**Comment by Christina-Lo** [comment]
This component has been released in Community DSM as well https://telus.invisionapp.com/dsm/telus/tds-community/folder/components/5b0eee0dbd61de0011520059

**Comment by varunj90** [comment]
assignees have been added on closed issue to reflect power level (points) on community heroes board (coming soon!)
