### ISSUE TITLE
new: BlockTextWithBorderAndIcon

### ISSUE THREAD

**Issue by joperron** [telus/tds-community#91]
## Problem Statement

We need to add this component to TDS so we can use it in Site Builder.

## Recommendation

* Develop a new component with the following fields: SVG icon & copy

## Designs

![screen shot 2018-08-22 at 12 54 27 pm](https://user-images.githubusercontent.com/1000260/44478087-94bb8080-a60a-11e8-8a3d-26a7d1a20cbb.png)

## Meta

* Willing to develop solution: Yes
* Has workaround: No
* Do any similar components already exist in TDS (core or community): No
* Does this pattern exist already but isn’t a community component? Unfortunately no.
* Which teams/applications do you think would use this improvement? Telus Health once again!
* High impact: No

**Comment by wascloud** [comment]
Is this design approved @lucylist ?

**Comment by joperron** [comment]
I believe this was approved by @gkychow

**Comment by varunj90** [comment]
based on my discussion with Phil Roberto, he was able to get the vendor to commit to only using type instead of icons (though it'll need to be .svgs still). given that design is approved by Phil, @gkychow and blessed by @lucylist - @joperron you are okay to create a sitebuilder block

cc: @nikaukraine

**Comment by nikaukraine** [comment]
@joperron if this will be a new community block, you still need to submit ticket with Site Builder https://github.com/telus/community-site-builder-blocks/issues providing the new design, thanks.

**Comment by joperron** [comment]
thanks guys, will submit today

**Comment by varunj90** [comment]
assignees have been added on closed issue to reflect power level (points) on community heroes board (coming soon!)
