### ISSUE TITLE
Quote icon (component)

### ISSUE THREAD

**Issue by nikaukraine** [telus/tds-community#92]
## In SiteBuilder we have BlockMarkdown with ability add **quote**, but it does not work, and we do not have it in TDS at the moment.
<img width="1440" alt="screen shot 2018-08-23 at 12 22 51 pm" src="https://user-images.githubusercontent.com/34170511/44538452-589e2380-a6cf-11e8-93f2-774abe02ff1e.png">

* As a Site Builder user , I would like to be able to add quote (generates a html blockquote) with BlockMarkdown, so that I can build pages with it

## Recommendation

Add this component into the TDS Components > Icons

## Designs

<img width="735" alt="screen shot 2018-08-23 at 12 17 20 pm" src="https://user-images.githubusercontent.com/34170511/44538182-9cdcf400-a6ce-11e8-8d35-c56e2eef6262.png"> 

## Meta

* Willing to design solution: No
* Willing to develop solution: No
* Has workaround: Yes (to not use quotes for now)
* Do any similar components already exist in TDS (core or community): Not sure (the rest of icons you have?)
* Does this pattern exist already but isn’t a community component? n/a
* Which teams/applications do you think would use this improvement? Telus Wise, Telus Health and other
* High impact: No

**Comment by wascloud** [comment]
DPA: This should definitely be TDS-Core

**Comment by varunj90** [comment]
@gkychow can you work with us to align on icon library.

cc: @lucylist

**Comment by theetrain** [comment]
We need a designer to own this.

**Comment by theetrain** [comment]
This is part of our backlog on standardizing icons. We will follow up once we enhance core-icon.

**Comment by gkychow** [comment]
@nikaukraine @varunj90 - I don't feel that we'll want to add this icon as part of our set and as a component. Though it was used for Health, the design that they created may not be what we want to use for quotes going forward.

**Comment by varunj90** [comment]
Closing this issue based on the comment above.

cc: @nikaukraine
